from OCC.Core.TopoDS import TopoDS_Shape
from typing import List,Set,Dict,Tuple

class ProjectInfo():
    projectName=""
    projectDir=""
    solverExe=""
    solverPath=""
    header1="--file version 1.16"
    header2="--generated by emx"
    header3="--the global settings  of project"
    param={
        "calculate_type":{"key":"caculate type","value":"0 1 1 0"},
        "power":{"key":"power(W)","value":"0"},
        "mpi":{"key":"mpi_num","value":"2"},
        "fre_start":{"key":"frequency_start(HZ)","value":"80000000"},
        "fre_end":{"key":"frequency_end(HZ)","value":"100000000"},
        "fre_inc":{"key":"frequency_incremet(HZ)","value":"3000000"},
        "root":{"key":"Root directory","value":""}
    }
