class FFR():
    classTitle="FarField Radiations"
    currentIndex=1
    titlePrefix="方向图"
    headers=[
        "--file version 1.0",
        "--generated by emx",
        "--Farfield Radiation"
        ]
    objIndex=256+1
    tipFFRNum="number_of_domain"
    tipTStart="theta_start(degree)"
    tipTEnd="theta_end(degree)"
    tipTInc="theta_increment(degree)"
    tipPStart="phi_start(degree)"
    tipPEnd="phi_end(degree)"
    tipPInc="phi_increment(degree)"
    def __init__(self) -> None:
        self.name:str=""
        self.title:str=""
        self.theStart:float=None
        self.theEnd:float=None
        self.theIncrement:float=None
        self.phiStart:float=None
        self.phiEnd:float=None
        self.phiIncrement:float=None
        self.freq:str="1e9"
        pass
        