from .port import Port
class Load():
    currentIndex=1
    titlePrefix="Load"
    objIndex=256+1
    headers=["--file version 1.16","--generated by emx","--the ports of receive","ports_num"]
    headerTitle="unit_code edge_point1 edge_point2 impedance(Ohm)_real impedance(Ohm)_imag receive_phase(degree)"
    def __init__(self) -> None:
        self.name:str=""
        self.title:str=""
        self.port:Port=None
        self.receive:int=None
        self.real:int=None
        self.imaginary:int=None