class NF():
    classTitle="Near fields"
    currentIndex=1
    titlePrefix="观察点"
    headers=[
        "--file version 1.0",
        "--generated by emx",
        "--Near field"
    ]
    tipNFNum="number_of_domain"
    tipUStart="u_start(m)"
    tipUEnd="u_end(m)"
    tipUInc="u_increment(m)"
    tipVStart="u_increment(m)"
    tipVEnd="v_end(m)"
    tipVInc="v_increment(m)"
    tipNStart="n_start(m)"
    tipNEnd="n_end(m)"
    tipNInc="n_increment(m)"
    objIndex=256+1
    color_default=(0.375,0.75,0)#0.375,0.75,0
    color_highlight=(0.7,0.7,0)
    color_highlight=(0,0,0.8)
    def __init__(self) -> None:
        self.name:str=""
        self.title:str=""
        self.uStart:float=0
        self.uEnd:float=0
        self.uIncrement:float=0
        self.vStart:float=0
        self.vEnd:float=0
        self.vIncrement:float=0
        self.nStart:float=0
        self.nEnd:float=0
        self.nIncrement:float=0
        self.show:bool=True
        self.axisType:int=0 #0:全局观察点 1：局部观察点 局部观察点选择为安装面，没有安装面时，使用全局坐标系
        self.pointType:int=0 # 0等间隔 1：离散点
        self.pointList:list=[]#离散点列表 （x,y,z）
    
        self.point_slice_start=-1
        self.point_slice_end=-1
        
        pass