class NFR():
    classTitle="NearField Radiations"
    currentIndex=1
    titlePrefix="NearField Rad"
    headers=[
        "--file version 1.0",
        "--generated by emx",
        "--Nearfield Radiation"
        ]
    objIndex=256+1
    tipFFRNum="number_of_domain"
    tipRadius="radius(m)"
    tipTStart="theta_start(degree)"
    tipTEnd="theta_end(degree)"
    tipTInc="theta_increment(degree)"
    tipPStart="phi_start(degree)"
    tipPEnd="phi_end(degree)"
    tipPInc="phi_increment(degree)"
    objIndex=256+1
    def __init__(self) -> None:
        self.name:str=""
        self.title:str=""
        self.theStart:float=None
        self.theEnd:float=None
        self.theIncrement:float=None
        self.phiStart:float=None
        self.phiEnd:float=None
        self.phiIncrement:float=None
        self.radius:float=None
        pass
        