from .port import Port
class Source():
    currentIndex=1
    titlePrefix="VoltageSource"
    objIndex=256+1
    nodeName="Sources"
    headers=[
        "--file version 1.16",
        "--generated by emx",
        "--the ports of transimit",
        "ports_num"
        ]
    headerTitle="unit_code edge_point1 edge_point2 source_magnitude source_phase(degree) impedance(Ohm)"
    def __init__(self) -> None:
        self.name:str=""
        self.title:str=""
        self.port:Port=None
        self.magnitude:int=None
        self.phase:int=None
        self.impedence:int=None