class projctTreeNodes():
    title="Navigation Tree"
    materials="Materials"
    media="Media"
    model="Model"
    mesh="Mesh"
    ports="Ports"
    excitations="Excitations"
    requests="Requests"
    results="Results"
    current="Currents"
    frequency="Frequency"
    sources="Sources"
    loads="Loads"
    power="Power[Total source power]"
    nfr="NearField Radiations"
    ffr="FarField Radiations"
    nf="Near fields"
    emi="EMI"
    nfr_prefix="NearField Rad"
    ffr_prefix="FarField Rad"
    nf_prefix="NearField"
    source_prefix="VoltageSource"
    result_extend="Extends"
    transmitters="TX/Transmitter"
    receivers="RX/Receiver"
    arrange="Arrangement"
    antena="Equivalent Source"
class nodeActions():
    run="Run"
    stop="Stop"
    save="Save"
    saveAs="Save As"
    rename="Rename"
    delete="Delete"
    importS="Import"
    export="Export"
    properties="Properties"
    showHide="Show/Hide"
    parallel="Parallel"
    addLoad="Add Load"
    addPort="Add Port"
    addSource="Add Source"
    createMesh="Create Mesh"
    power="Power"
    nfr="NearField Radiations"
    ffr="FarField Radiations"
    nf="Near fields"
    emi="EMI"
    import_array="Import Antenna Array"
    import_radio="Import Radio Pattern"
    media_library="Media Library"
    t_array="Array"
    t_points="Points"
    medial_setting="Medium Settings"
    show_hide="Show/Hide"







