class projctTreeNodes():
    title="Navigation Tree"
    materials="Materials"
    component="组件"
    faces="面"
    shapes="实体"
    media="材料"
    model="模型"
    mesh="网格"
    ports="Ports"
    excitations="边界/源"
    requests="求解设置"
    reqTime="时间设置"
    reqFFR="方向图"
    reqNF="观察点"
    reqDomain="观察域"
    reqThermal="温度"
    results="结果分析"
    results_extend="外部数据"
    result_em="电场值"
    result_em_nf="观察点"
    result_em_domain="观察域"
    result_ffr="方向图"
    result_thermal="温度值"
    result_thermal_3d="观察域"
    result_thermal_2d="观察点"
    result_struct="位移量"
    result_struct_3d="观察域"
    current="表面电流"
    frequency="求解参数"
    sources="Sources"
    loads="Loads"
    power="Power[Total source power]"
    nfr="NearField Radiations"
    
    emi="电磁干扰"
    nfr_prefix="NearField Rad"
    ffr_prefix="FarField Rad"
    nf_prefix="观察点"
    source_prefix="VoltageSource"
    
    transmitters="发射天线"
    receivers="电磁干扰"
    arrange="Arrangement"
    antena="Equivalent Source"
    mediumModel="整体材料"
    mediumBase="本体材料"
    mediumCoat="涂覆材料"
    pf="物理场"
    pf_boundary="边界/源"
    pf_em="电磁"
    pf_em_pec="PEC"
    pf_em_pml="完美匹配层"
    pf_em_exf="外推面"
    #电路节点
    pf_circuit="电路"
    pf_circuit_source="源"
    pf_circuit_load="负载"
    pf_thermal="热"
    pf_thermal_dirichlet="固定温度"
    pf_thermal_convection="热对流"
    pf_thermal_radiation="热辐射"
    pf_thermal_source="热源"
    pf_struct="结构"
    pf_struct_dirichlet="固定位移"
    pf_struct_force="外力"
    
    
    
    
class nodeActions():
    run="运行"
    stop="停止"
    save="保存"
    saveAs="另存为"
    rename="重命名"
    delete="删除"
    modify="编辑"
    importS="导入"
    export="导出"
    properties="设置"
    showHide="显示/隐藏"
    parallel="Parallel"
    addLoad="Add Load"
    addPort="Add Port"
    addSource="Add Source"
    createMesh="生成网格"
    power="Power"
    nfr="NearField Radiations"
    ffr="FarField Radiations"
    nf="电磁环境"
    emi="EMI"
    import_array="Import Antenna Array"
    import_radio="Import Radio Pattern"
    media_library="材料管理"
    mesh_size="网格尺寸"
    t_array="Array"
    t_points="Points"
    medial_setting="材料设置"
    show_hide="Show/Hide"
    reverseNormal="法向反转"
    mediumBase="本体材料"
    mediumCoat="涂覆材料"
    pf_em="电磁"
    #电路节点
    pf_circuit="电路"
    pf_thermal="热"
    pf_structure="结构"
    create="创建"
    clear="清除"
    pml_exf="PML/外推面"






