# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmDomain_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmDomain(object):
    def setupUi(self, frmDomain):
        frmDomain.setObjectName("frmDomain")
        frmDomain.resize(323, 249)
        self.centralwidget = QtWidgets.QWidget(frmDomain)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 210, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(180, 210, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxDomain = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxDomain.setGeometry(QtCore.QRect(10, 10, 301, 191))
        self.gbxDomain.setObjectName("gbxDomain")
        self.checkBox = QtWidgets.QCheckBox(self.gbxDomain)
        self.checkBox.setGeometry(QtCore.QRect(20, 30, 91, 30))
        self.checkBox.setObjectName("checkBox")
        self.label_5 = QtWidgets.QLabel(self.gbxDomain)
        self.label_5.setGeometry(QtCore.QRect(120, 30, 91, 30))
        self.label_5.setObjectName("label_5")
        self.txtTimeStepNum = QtWidgets.QLineEdit(self.gbxDomain)
        self.txtTimeStepNum.setGeometry(QtCore.QRect(220, 30, 71, 30))
        self.txtTimeStepNum.setObjectName("txtTimeStepNum")
        self.checkBox_2 = QtWidgets.QCheckBox(self.gbxDomain)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 70, 81, 30))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_6 = QtWidgets.QLabel(self.gbxDomain)
        self.label_6.setGeometry(QtCore.QRect(120, 70, 91, 30))
        self.label_6.setObjectName("label_6")
        self.txtTimeStepNum_2 = QtWidgets.QLineEdit(self.gbxDomain)
        self.txtTimeStepNum_2.setGeometry(QtCore.QRect(220, 70, 71, 30))
        self.txtTimeStepNum_2.setObjectName("txtTimeStepNum_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.gbxDomain)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 110, 81, 30))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_7 = QtWidgets.QLabel(self.gbxDomain)
        self.label_7.setGeometry(QtCore.QRect(120, 110, 91, 30))
        self.label_7.setObjectName("label_7")
        self.txtTimeStepNum_3 = QtWidgets.QLineEdit(self.gbxDomain)
        self.txtTimeStepNum_3.setGeometry(QtCore.QRect(220, 110, 71, 30))
        self.txtTimeStepNum_3.setObjectName("txtTimeStepNum_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.gbxDomain)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 150, 81, 30))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_8 = QtWidgets.QLabel(self.gbxDomain)
        self.label_8.setGeometry(QtCore.QRect(120, 150, 91, 30))
        self.label_8.setObjectName("label_8")
        self.txtTimeStepNum_4 = QtWidgets.QLineEdit(self.gbxDomain)
        self.txtTimeStepNum_4.setGeometry(QtCore.QRect(220, 150, 71, 30))
        self.txtTimeStepNum_4.setObjectName("txtTimeStepNum_4")
        frmDomain.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmDomain)
        QtCore.QMetaObject.connectSlotsByName(frmDomain)
        frmDomain.setTabOrder(self.txtTimeStepNum, self.btnOK)
        frmDomain.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmDomain):
        _translate = QtCore.QCoreApplication.translate
        frmDomain.setWindowTitle(_translate("frmDomain", "观察域"))
        self.btnOK.setText(_translate("frmDomain", "确定"))
        self.btnCancel.setText(_translate("frmDomain", "取消"))
        self.gbxDomain.setTitle(_translate("frmDomain", "求解域选择"))
        self.checkBox.setText(_translate("frmDomain", "电磁"))
        self.label_5.setText(_translate("frmDomain", "时间步数"))
        self.txtTimeStepNum.setText(_translate("frmDomain", "1"))
        self.checkBox_2.setText(_translate("frmDomain", "电路"))
        self.label_6.setText(_translate("frmDomain", "时间步数"))
        self.txtTimeStepNum_2.setText(_translate("frmDomain", "1"))
        self.checkBox_3.setText(_translate("frmDomain", "热"))
        self.label_7.setText(_translate("frmDomain", "时间步数"))
        self.txtTimeStepNum_3.setText(_translate("frmDomain", "1"))
        self.checkBox_4.setText(_translate("frmDomain", "结构"))
        self.label_8.setText(_translate("frmDomain", "时间步数"))
        self.txtTimeStepNum_4.setText(_translate("frmDomain", "1"))
