# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmAtenna.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmScalar(object):
    def setupUi(self, frmScalar):
        frmScalar.setObjectName("frmScalar")
        frmScalar.resize(489, 451)
        self.centralwidget = QtWidgets.QWidget(frmScalar)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 451, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tabScaleRange = QtWidgets.QWidget()
        self.tabScaleRange.setObjectName("tabScaleRange")
        self.groupBox = QtWidgets.QGroupBox(self.tabScaleRange)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 421, 291))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 101, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 101, 25))
        self.label_3.setObjectName("label_3")
        self.txtMax = QtWidgets.QLineEdit(self.groupBox)
        self.txtMax.setEnabled(False)
        self.txtMax.setGeometry(QtCore.QRect(160, 130, 221, 25))
        self.txtMax.setObjectName("txtMax")
        self.txtMin = QtWidgets.QLineEdit(self.groupBox)
        self.txtMin.setEnabled(False)
        self.txtMin.setGeometry(QtCore.QRect(160, 170, 221, 25))
        self.txtMin.setObjectName("txtMin")
        self.rdbAuto = QtWidgets.QRadioButton(self.groupBox)
        self.rdbAuto.setGeometry(QtCore.QRect(10, 30, 401, 26))
        self.rdbAuto.setObjectName("rdbAuto")
        self.rdbFixed = QtWidgets.QRadioButton(self.groupBox)
        self.rdbFixed.setGeometry(QtCore.QRect(10, 70, 401, 26))
        self.rdbFixed.setObjectName("rdbFixed")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 141, 25))
        self.label_4.setObjectName("label_4")
        self.txtNumOfColors = QtWidgets.QLineEdit(self.groupBox)
        self.txtNumOfColors.setEnabled(True)
        self.txtNumOfColors.setGeometry(QtCore.QRect(160, 210, 221, 25))
        self.txtNumOfColors.setObjectName("txtNumOfColors")
        self.tabWidget.addTab(self.tabScaleRange, "")
        self.tabAdvanced = QtWidgets.QWidget()
        self.tabAdvanced.setObjectName("tabAdvanced")
        self.tabWidget.addTab(self.tabAdvanced, "")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(100, 390, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(190, 390, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(280, 390, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        frmScalar.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmScalar)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmScalar)

    def retranslateUi(self, frmScalar):
        _translate = QtCore.QCoreApplication.translate
        frmScalar.setWindowTitle(_translate("frmScalar", "Scale range settings"))
        self.groupBox.setTitle(_translate("frmScalar", "Linear scale"))
        self.label_2.setText(_translate("frmScalar", "Maximum"))
        self.label_3.setText(_translate("frmScalar", "Minimum"))
        self.rdbAuto.setText(_translate("frmScalar", "Automatically detemined from data range"))
        self.rdbFixed.setText(_translate("frmScalar", "Fixed range"))
        self.label_4.setText(_translate("frmScalar", "NumberOfColors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabScaleRange), _translate("frmScalar", "Scale range"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvanced), _translate("frmScalar", "Advanced"))
        self.btnOK.setText(_translate("frmScalar", "OK"))
        self.btnApply.setText(_translate("frmScalar", "Apply"))
        self.btnCancel.setText(_translate("frmScalar", "Cancel"))
