# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmEM.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmEM(object):
    def setupUi(self, frmEM):
        frmEM.setObjectName("frmEM")
        frmEM.resize(409, 409)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmEM.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmEM)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 15, 391, 351))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tbFaces = QtWidgets.QTableWidget(self.groupBox_2)
        self.tbFaces.setGeometry(QtCore.QRect(5, 20, 381, 291))
        self.tbFaces.setObjectName("tbFaces")
        self.tbFaces.setColumnCount(2)
        self.tbFaces.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tbFaces.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tbFaces.setHorizontalHeaderItem(1, item)
        self.btnClear = QtWidgets.QToolButton(self.groupBox_2)
        self.btnClear.setGeometry(QtCore.QRect(5, 315, 121, 26))
        self.btnClear.setObjectName("btnClear")
        self.btnRemove = QtWidgets.QPushButton(self.groupBox_2)
        self.btnRemove.setGeometry(QtCore.QRect(260, 315, 121, 26))
        self.btnRemove.setObjectName("btnRemove")
        self.btnApply = QtWidgets.QToolButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(160, 370, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(50, 370, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnClose = QtWidgets.QToolButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(270, 370, 80, 30))
        self.btnClose.setObjectName("btnClose")
        frmEM.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmEM)
        QtCore.QMetaObject.connectSlotsByName(frmEM)

    def retranslateUi(self, frmEM):
        _translate = QtCore.QCoreApplication.translate
        frmEM.setWindowTitle(_translate("frmEM", "物理场-电磁"))
        self.groupBox_2.setTitle(_translate("frmEM", "边界条件列表"))
        item = self.tbFaces.horizontalHeaderItem(0)
        item.setText(_translate("frmEM", "面编号"))
        item = self.tbFaces.horizontalHeaderItem(1)
        item.setText(_translate("frmEM", "边界条件"))
        self.btnClear.setText(_translate("frmEM", "移除全部"))
        self.btnRemove.setText(_translate("frmEM", "移除选中行"))
        self.btnApply.setText(_translate("frmEM", "应用"))
        self.btnOK.setText(_translate("frmEM", "确定"))
        self.btnClose.setText(_translate("frmEM", "取消"))
