# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmStartUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmStartup(object):
    def setupUi(self, frmStartup):
        frmStartup.setObjectName("frmStartup")
        frmStartup.setWindowModality(QtCore.Qt.WindowModal)
        frmStartup.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(frmStartup)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("d:\\project\\cae\\fem-gdtd\\src2\\UI\\../icons/startup.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        frmStartup.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmStartup)
        QtCore.QMetaObject.connectSlotsByName(frmStartup)

    def retranslateUi(self, frmStartup):
        _translate = QtCore.QCoreApplication.translate
        frmStartup.setWindowTitle(_translate("frmStartup", "Simulation parallel "))
import icons_rc
