# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmStruct.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmThermalSource(object):
    def setupUi(self, frmThermalSource):
        frmThermalSource.setObjectName("frmThermalSource")
        frmThermalSource.resize(308, 192)
        self.centralwidget = QtWidgets.QWidget(frmThermalSource)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(110, 140, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 140, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK_2.setGeometry(QtCore.QRect(20, 140, 80, 30))
        self.btnOK_2.setObjectName("btnOK_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 60, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txtPower_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPower_2.setGeometry(QtCore.QRect(90, 70, 181, 30))
        self.txtPower_2.setObjectName("txtPower_2")
        self.txtPower = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPower.setGeometry(QtCore.QRect(90, 30, 181, 30))
        self.txtPower.setObjectName("txtPower")
        frmThermalSource.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmThermalSource)
        QtCore.QMetaObject.connectSlotsByName(frmThermalSource)

    def retranslateUi(self, frmThermalSource):
        _translate = QtCore.QCoreApplication.translate
        frmThermalSource.setWindowTitle(_translate("frmThermalSource", "热-热源"))
        self.btnOK.setText(_translate("frmThermalSource", "应用"))
        self.btnCancel.setText(_translate("frmThermalSource", "取消"))
        self.btnOK_2.setText(_translate("frmThermalSource", "确定"))
        self.label_3.setText(_translate("frmThermalSource", "功率"))
        self.label.setText(_translate("frmThermalSource", "面编号"))
