# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmExchange.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmExchange(object):
    def setupUi(self, frmExchange):
        frmExchange.setObjectName("frmExchange")
        frmExchange.setWindowModality(QtCore.Qt.WindowModal)
        frmExchange.resize(402, 221)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmExchange.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmExchange)
        self.centralwidget.setObjectName("centralwidget")
        self.lblProject = QtWidgets.QLabel(self.centralwidget)
        self.lblProject.setGeometry(QtCore.QRect(10, 50, 71, 25))
        self.lblProject.setObjectName("lblProject")
        self.lblSimulation = QtWidgets.QLabel(self.centralwidget)
        self.lblSimulation.setGeometry(QtCore.QRect(10, 100, 71, 25))
        self.lblSimulation.setObjectName("lblSimulation")
        self.txtSourceFile = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSourceFile.setGeometry(QtCore.QRect(90, 50, 221, 25))
        self.txtSourceFile.setObjectName("txtSourceFile")
        self.txtTargetFile = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTargetFile.setGeometry(QtCore.QRect(90, 100, 221, 25))
        self.txtTargetFile.setObjectName("txtTargetFile")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(90, 170, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnBrowseSource = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowseSource.setGeometry(QtCore.QRect(320, 50, 61, 25))
        self.btnBrowseSource.setObjectName("btnBrowseSource")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(230, 170, 80, 30))
        self.btnClose.setObjectName("btnClose")
        self.btnBrowseTarget = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowseTarget.setGeometry(QtCore.QRect(320, 100, 61, 25))
        self.btnBrowseTarget.setObjectName("btnBrowseTarget")
        frmExchange.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmExchange)
        QtCore.QMetaObject.connectSlotsByName(frmExchange)

    def retranslateUi(self, frmExchange):
        _translate = QtCore.QCoreApplication.translate
        frmExchange.setWindowTitle(_translate("frmExchange", "模型格式转换"))
        self.lblProject.setText(_translate("frmExchange", "源文件"))
        self.lblSimulation.setText(_translate("frmExchange", "目标文件"))
        self.btnOK.setText(_translate("frmExchange", "确定"))
        self.btnBrowseSource.setText(_translate("frmExchange", "浏览"))
        self.btnClose.setText(_translate("frmExchange", "取消"))
        self.btnBrowseTarget.setText(_translate("frmExchange", "浏览"))
