# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmCircuitModify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmPower(object):
    def setupUi(self, frmPower):
        frmPower.setObjectName("frmPower")
        frmPower.resize(383, 193)
        self.centralwidget = QtWidgets.QWidget(frmPower)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 131, 30))
        self.label.setObjectName("label")
        self.txtPower = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPower.setGeometry(QtCore.QRect(180, 60, 151, 30))
        self.txtPower.setObjectName("txtPower")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(110, 120, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(210, 120, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 231, 25))
        self.label_2.setObjectName("label_2")
        frmPower.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmPower)
        QtCore.QMetaObject.connectSlotsByName(frmPower)

    def retranslateUi(self, frmPower):
        _translate = QtCore.QCoreApplication.translate
        frmPower.setWindowTitle(_translate("frmPower", "Power settings"))
        self.label.setText(_translate("frmPower", "Source power(W)"))
        self.btnOK.setText(_translate("frmPower", "OK"))
        self.btnCancel.setText(_translate("frmPower", "Cancel"))
        self.label_2.setText(_translate("frmPower", "Element source power"))
