# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmMediaCoat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMediaCoat(object):
    def setupUi(self, frmMediaCoat):
        frmMediaCoat.setObjectName("frmMediaCoat")
        frmMediaCoat.resize(351, 156)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMediaCoat.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmMediaCoat)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(160, 110, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 101, 30))
        self.label_6.setObjectName("label_6")
        self.btnClose = QtWidgets.QToolButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(260, 110, 80, 30))
        self.btnClose.setObjectName("btnClose")
        self.txtMediaName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMediaName.setEnabled(False)
        self.txtMediaName.setGeometry(QtCore.QRect(120, 20, 150, 30))
        self.txtMediaName.setText("")
        self.txtMediaName.setReadOnly(True)
        self.txtMediaName.setObjectName("txtMediaName")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 101, 30))
        self.label_7.setObjectName("label_7")
        self.txtThickness = QtWidgets.QLineEdit(self.centralwidget)
        self.txtThickness.setGeometry(QtCore.QRect(120, 60, 150, 30))
        self.txtThickness.setText("")
        self.txtThickness.setObjectName("txtThickness")
        self.btnChoose = QtWidgets.QPushButton(self.centralwidget)
        self.btnChoose.setGeometry(QtCore.QRect(280, 20, 61, 30))
        self.btnChoose.setObjectName("btnChoose")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(10, 110, 80, 30))
        self.btnClear.setObjectName("btnClear")
        frmMediaCoat.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMediaCoat)
        QtCore.QMetaObject.connectSlotsByName(frmMediaCoat)

    def retranslateUi(self, frmMediaCoat):
        _translate = QtCore.QCoreApplication.translate
        frmMediaCoat.setWindowTitle(_translate("frmMediaCoat", "涂覆材料"))
        self.btnOK.setText(_translate("frmMediaCoat", "确定"))
        self.label_6.setText(_translate("frmMediaCoat", "涂覆介质"))
        self.btnClose.setText(_translate("frmMediaCoat", "取消"))
        self.label_7.setText(_translate("frmMediaCoat", "涂覆厚度(m)"))
        self.btnChoose.setText(_translate("frmMediaCoat", "选择"))
        self.btnClear.setText(_translate("frmMediaCoat", "清空"))
