# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmCreateLoad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmLoad(object):
    def setupUi(self, frmLoad):
        frmLoad.setObjectName("frmLoad")
        frmLoad.resize(402, 406)
        self.centralwidget = QtWidgets.QWidget(frmLoad)
        self.centralwidget.setObjectName("centralwidget")
        self.lblPort = QtWidgets.QLabel(self.centralwidget)
        self.lblPort.setGeometry(QtCore.QRect(30, 30, 81, 30))
        self.lblPort.setObjectName("lblPort")
        self.cbxPort = QtWidgets.QComboBox(self.centralwidget)
        self.cbxPort.setGeometry(QtCore.QRect(120, 30, 201, 30))
        self.cbxPort.setObjectName("cbxPort")
        self.cbxPort.addItem("")
        self.cbxPort.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 130, 301, 131))
        self.groupBox.setObjectName("groupBox")
        self.lblReal = QtWidgets.QLabel(self.groupBox)
        self.lblReal.setGeometry(QtCore.QRect(10, 40, 141, 25))
        self.lblReal.setObjectName("lblReal")
        self.lblImag = QtWidgets.QLabel(self.groupBox)
        self.lblImag.setGeometry(QtCore.QRect(10, 80, 141, 25))
        self.lblImag.setObjectName("lblImag")
        self.txtReal = QtWidgets.QLineEdit(self.groupBox)
        self.txtReal.setGeometry(QtCore.QRect(150, 40, 141, 30))
        self.txtReal.setObjectName("txtReal")
        self.txtImag = QtWidgets.QLineEdit(self.groupBox)
        self.txtImag.setGeometry(QtCore.QRect(150, 80, 141, 30))
        self.txtImag.setObjectName("txtImag")
        self.txtReceive = QtWidgets.QLineEdit(self.centralwidget)
        self.txtReceive.setGeometry(QtCore.QRect(180, 80, 141, 30))
        self.txtReceive.setObjectName("txtReceive")
        self.lblReal_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblReal_2.setGeometry(QtCore.QRect(30, 80, 141, 30))
        self.lblReal_2.setObjectName("lblReal_2")
        self.btnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreate.setGeometry(QtCore.QRect(50, 350, 80, 30))
        self.btnCreate.setObjectName("btnCreate")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(150, 350, 80, 30))
        self.btnAdd.setObjectName("btnAdd")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(250, 350, 80, 30))
        self.btnClose.setObjectName("btnClose")
        self.txtLoadName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLoadName.setGeometry(QtCore.QRect(120, 290, 201, 30))
        self.txtLoadName.setObjectName("txtLoadName")
        self.lblLoadName = QtWidgets.QLabel(self.centralwidget)
        self.lblLoadName.setGeometry(QtCore.QRect(30, 290, 71, 30))
        self.lblLoadName.setObjectName("lblLoadName")
        frmLoad.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmLoad)
        QtCore.QMetaObject.connectSlotsByName(frmLoad)

    def retranslateUi(self, frmLoad):
        _translate = QtCore.QCoreApplication.translate
        frmLoad.setWindowTitle(_translate("frmLoad", "Create load"))
        self.lblPort.setText(_translate("frmLoad", "Port"))
        self.cbxPort.setItemText(0, _translate("frmLoad", "Port1"))
        self.cbxPort.setItemText(1, _translate("frmLoad", "Port2"))
        self.groupBox.setTitle(_translate("frmLoad", "Comlex impendence(Ohm)"))
        self.lblReal.setText(_translate("frmLoad", "Real part"))
        self.lblImag.setText(_translate("frmLoad", "Imaginary part"))
        self.lblReal_2.setText(_translate("frmLoad", "Receive(degree)"))
        self.btnCreate.setText(_translate("frmLoad", "Create"))
        self.btnAdd.setText(_translate("frmLoad", "Add"))
        self.btnClose.setText(_translate("frmLoad", "Close"))
        self.lblLoadName.setText(_translate("frmLoad", "Label"))
