# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmModelMedia copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmModelMedia(object):
    def setupUi(self, frmModelMedia):
        frmModelMedia.setObjectName("frmModelMedia")
        frmModelMedia.resize(409, 462)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmModelMedia.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmModelMedia)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 391, 346))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tbFaces = QtWidgets.QTableWidget(self.groupBox_2)
        self.tbFaces.setGeometry(QtCore.QRect(5, 20, 381, 291))
        self.tbFaces.setObjectName("tbFaces")
        self.tbFaces.setColumnCount(4)
        self.tbFaces.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tbFaces.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tbFaces.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbFaces.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbFaces.setHorizontalHeaderItem(3, item)
        self.btnClear = QtWidgets.QToolButton(self.groupBox_2)
        self.btnClear.setGeometry(QtCore.QRect(5, 315, 121, 26))
        self.btnClear.setObjectName("btnClear")
        self.btnRemove = QtWidgets.QPushButton(self.groupBox_2)
        self.btnRemove.setGeometry(QtCore.QRect(260, 315, 121, 26))
        self.btnRemove.setObjectName("btnRemove")
        self.btnApply = QtWidgets.QToolButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(160, 420, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(50, 420, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 101, 30))
        self.label_6.setObjectName("label_6")
        self.cbxMedia = QtWidgets.QComboBox(self.centralwidget)
        self.cbxMedia.setGeometry(QtCore.QRect(130, 20, 181, 30))
        self.cbxMedia.setObjectName("cbxMedia")
        self.btnMore = QtWidgets.QToolButton(self.centralwidget)
        self.btnMore.setGeometry(QtCore.QRect(320, 20, 76, 30))
        self.btnMore.setObjectName("btnMore")
        self.btnClose = QtWidgets.QToolButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(270, 420, 80, 30))
        self.btnClose.setObjectName("btnClose")
        frmModelMedia.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmModelMedia)
        QtCore.QMetaObject.connectSlotsByName(frmModelMedia)

    def retranslateUi(self, frmModelMedia):
        _translate = QtCore.QCoreApplication.translate
        frmModelMedia.setWindowTitle(_translate("frmModelMedia", "模型材料"))
        self.groupBox_2.setTitle(_translate("frmModelMedia", "模型面设置(CTRL+鼠标左键点击选择面)"))
        item = self.tbFaces.horizontalHeaderItem(0)
        item.setText(_translate("frmModelMedia", "面"))
        item = self.tbFaces.horizontalHeaderItem(1)
        item.setText(_translate("frmModelMedia", "本体材料"))
        item = self.tbFaces.horizontalHeaderItem(2)
        item.setText(_translate("frmModelMedia", "涂覆介质"))
        item = self.tbFaces.horizontalHeaderItem(3)
        item.setText(_translate("frmModelMedia", "涂覆厚度"))
        self.btnClear.setText(_translate("frmModelMedia", "移除全部"))
        self.btnRemove.setText(_translate("frmModelMedia", "移除选中行"))
        self.btnApply.setText(_translate("frmModelMedia", "应用"))
        self.btnOK.setText(_translate("frmModelMedia", "确定"))
        self.label_6.setText(_translate("frmModelMedia", "模型整体材料"))
        self.btnMore.setText(_translate("frmModelMedia", "材料库"))
        self.btnClose.setText(_translate("frmModelMedia", "取消"))
