# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmVoltageSource.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmVoltageSource(object):
    def setupUi(self, frmVoltageSource):
        frmVoltageSource.setObjectName("frmVoltageSource")
        frmVoltageSource.resize(433, 390)
        self.centralwidget = QtWidgets.QWidget(frmVoltageSource)
        self.centralwidget.setObjectName("centralwidget")
        self.lblPort = QtWidgets.QLabel(self.centralwidget)
        self.lblPort.setGeometry(QtCore.QRect(20, 20, 51, 30))
        self.lblPort.setObjectName("lblPort")
        self.cbxPort = QtWidgets.QComboBox(self.centralwidget)
        self.cbxPort.setGeometry(QtCore.QRect(80, 20, 341, 30))
        self.cbxPort.setObjectName("cbxPort")
        self.cbxPort.addItem("")
        self.cbxPort.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 411, 161))
        self.groupBox.setObjectName("groupBox")
        self.lblMagitude = QtWidgets.QLabel(self.groupBox)
        self.lblMagitude.setGeometry(QtCore.QRect(10, 30, 236, 30))
        self.lblMagitude.setObjectName("lblMagitude")
        self.lblPhase = QtWidgets.QLabel(self.groupBox)
        self.lblPhase.setGeometry(QtCore.QRect(10, 70, 236, 30))
        self.lblPhase.setObjectName("lblPhase")
        self.lblImpedence = QtWidgets.QLabel(self.groupBox)
        self.lblImpedence.setGeometry(QtCore.QRect(10, 110, 236, 30))
        self.lblImpedence.setObjectName("lblImpedence")
        self.txtMagnitude = QtWidgets.QLineEdit(self.groupBox)
        self.txtMagnitude.setGeometry(QtCore.QRect(250, 30, 150, 30))
        self.txtMagnitude.setObjectName("txtMagnitude")
        self.txtPhase = QtWidgets.QLineEdit(self.groupBox)
        self.txtPhase.setGeometry(QtCore.QRect(250, 70, 150, 30))
        self.txtPhase.setObjectName("txtPhase")
        self.txtImpedence = QtWidgets.QLineEdit(self.groupBox)
        self.txtImpedence.setGeometry(QtCore.QRect(250, 110, 150, 30))
        self.txtImpedence.setObjectName("txtImpedence")
        self.txtSourceName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSourceName.setGeometry(QtCore.QRect(80, 250, 341, 30))
        self.txtSourceName.setObjectName("txtSourceName")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 51, 30))
        self.label_5.setObjectName("label_5")
        self.btnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreate.setGeometry(QtCore.QRect(90, 320, 80, 30))
        self.btnCreate.setObjectName("btnCreate")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(190, 320, 80, 30))
        self.btnAdd.setObjectName("btnAdd")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(290, 320, 80, 30))
        self.btnClose.setObjectName("btnClose")
        frmVoltageSource.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmVoltageSource)
        QtCore.QMetaObject.connectSlotsByName(frmVoltageSource)

    def retranslateUi(self, frmVoltageSource):
        _translate = QtCore.QCoreApplication.translate
        frmVoltageSource.setWindowTitle(_translate("frmVoltageSource", "Add voltage source"))
        self.lblPort.setText(_translate("frmVoltageSource", "Port"))
        self.cbxPort.setItemText(0, _translate("frmVoltageSource", "Port1"))
        self.cbxPort.setItemText(1, _translate("frmVoltageSource", "Port2"))
        self.groupBox.setTitle(_translate("frmVoltageSource", "Voltage"))
        self.lblMagitude.setText(_translate("frmVoltageSource", "Magnitude(V）"))
        self.lblPhase.setText(_translate("frmVoltageSource", "Phase(degrees)"))
        self.lblImpedence.setText(_translate("frmVoltageSource", "Reference impedence(Ohm)"))
        self.label_5.setText(_translate("frmVoltageSource", "Label"))
        self.btnCreate.setText(_translate("frmVoltageSource", "Create"))
        self.btnAdd.setText(_translate("frmVoltageSource", "Add"))
        self.btnClose.setText(_translate("frmVoltageSource", "Close"))
