# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmSBoundGate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmSBoundGate(object):
    def setupUi(self, frmSBoundGate):
        frmSBoundGate.setObjectName("frmSBoundGate")
        frmSBoundGate.resize(329, 283)
        self.centralwidget = QtWidgets.QWidget(frmSBoundGate)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(120, 240, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(220, 240, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 240, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.groupCondition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCondition.setGeometry(QtCore.QRect(10, 20, 301, 211))
        self.groupCondition.setTitle("")
        self.groupCondition.setObjectName("groupCondition")
        self.txtFaceId = QtWidgets.QLineEdit(self.groupCondition)
        self.txtFaceId.setGeometry(QtCore.QRect(120, 10, 161, 30))
        self.txtFaceId.setObjectName("txtFaceId")
        self.label = QtWidgets.QLabel(self.groupCondition)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupCondition)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 101, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtPerm = QtWidgets.QLineEdit(self.groupCondition)
        self.txtPerm.setGeometry(QtCore.QRect(120, 90, 161, 30))
        self.txtPerm.setObjectName("txtPerm")
        self.label_4 = QtWidgets.QLabel(self.groupCondition)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 101, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.txtThickness = QtWidgets.QLineEdit(self.groupCondition)
        self.txtThickness.setGeometry(QtCore.QRect(120, 130, 161, 30))
        self.txtThickness.setObjectName("txtThickness")
        self.txtFunc = QtWidgets.QLineEdit(self.groupCondition)
        self.txtFunc.setGeometry(QtCore.QRect(120, 170, 161, 30))
        self.txtFunc.setObjectName("txtFunc")
        self.label_5 = QtWidgets.QLabel(self.groupCondition)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 101, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupCondition)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 101, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.txtVoltage = QtWidgets.QLineEdit(self.groupCondition)
        self.txtVoltage.setGeometry(QtCore.QRect(120, 50, 161, 30))
        self.txtVoltage.setObjectName("txtVoltage")
        frmSBoundGate.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmSBoundGate)
        QtCore.QMetaObject.connectSlotsByName(frmSBoundGate)

    def retranslateUi(self, frmSBoundGate):
        _translate = QtCore.QCoreApplication.translate
        frmSBoundGate.setWindowTitle(_translate("frmSBoundGate", "薄绝缘栅"))
        self.btnApply.setText(_translate("frmSBoundGate", "应用"))
        self.btnCancel.setText(_translate("frmSBoundGate", "取消"))
        self.btnOK.setText(_translate("frmSBoundGate", "确定"))
        self.label.setText(_translate("frmSBoundGate", "面编号"))
        self.label_3.setText(_translate("frmSBoundGate", "相对介电常数"))
        self.label_4.setText(_translate("frmSBoundGate", "氧化层厚度(m)"))
        self.label_5.setText(_translate("frmSBoundGate", "金属功函数(V)"))
        self.label_6.setText(_translate("frmSBoundGate", "直流源幅度(V)"))
