# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmMediaModify - 副本.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMediaModify(object):
    def setupUi(self, frmMediaModify):
        frmMediaModify.setObjectName("frmMediaModify")
        frmMediaModify.resize(389, 366)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMediaModify.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmMediaModify)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 25))
        self.label.setObjectName("label")
        self.txtMediaName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMediaName.setGeometry(QtCore.QRect(160, 20, 211, 25))
        self.txtMediaName.setObjectName("txtMediaName")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 371, 261))
        self.groupBox.setObjectName("groupBox")
        self.btnAddFreq = QtWidgets.QPushButton(self.groupBox)
        self.btnAddFreq.setGeometry(QtCore.QRect(10, 220, 121, 25))
        self.btnAddFreq.setObjectName("btnAddFreq")
        self.btnRemoveFreq = QtWidgets.QPushButton(self.groupBox)
        self.btnRemoveFreq.setGeometry(QtCore.QRect(240, 220, 121, 25))
        self.btnRemoveFreq.setObjectName("btnRemoveFreq")
        self.tbFreqList = QtWidgets.QTableWidget(self.groupBox)
        self.tbFreqList.setGeometry(QtCore.QRect(10, 40, 351, 171))
        self.tbFreqList.setObjectName("tbFreqList")
        self.tbFreqList.setColumnCount(0)
        self.tbFreqList.setRowCount(0)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(290, 330, 80, 30))
        self.btnClose.setObjectName("btnClose")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 330, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(160, 330, 80, 30))
        self.btnApply.setObjectName("btnApply")
        frmMediaModify.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMediaModify)
        QtCore.QMetaObject.connectSlotsByName(frmMediaModify)

    def retranslateUi(self, frmMediaModify):
        _translate = QtCore.QCoreApplication.translate
        frmMediaModify.setWindowTitle(_translate("frmMediaModify", "材料修改"))
        self.label.setText(_translate("frmMediaModify", "材料名称"))
        self.groupBox.setTitle(_translate("frmMediaModify", "属性"))
        self.btnAddFreq.setText(_translate("frmMediaModify", "增加频点"))
        self.btnRemoveFreq.setText(_translate("frmMediaModify", "移除频点"))
        self.btnClose.setText(_translate("frmMediaModify", "取消"))
        self.btnOK.setText(_translate("frmMediaModify", "确定"))
        self.btnApply.setText(_translate("frmMediaModify", "应用"))
