# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmPostParam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmPostParam(object):
    def setupUi(self, frmPostParam):
        frmPostParam.setObjectName("frmPostParam")
        frmPostParam.resize(323, 119)
        self.centralwidget = QtWidgets.QWidget(frmPostParam)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 80, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(180, 80, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxDomain = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxDomain.setGeometry(QtCore.QRect(10, 10, 301, 61))
        self.gbxDomain.setObjectName("gbxDomain")
        self.chk1 = QtWidgets.QCheckBox(self.gbxDomain)
        self.chk1.setGeometry(QtCore.QRect(40, 20, 91, 30))
        self.chk1.setChecked(True)
        self.chk1.setObjectName("chk1")
        self.chk2 = QtWidgets.QCheckBox(self.gbxDomain)
        self.chk2.setGeometry(QtCore.QRect(170, 20, 121, 30))
        self.chk2.setChecked(True)
        self.chk2.setObjectName("chk2")
        frmPostParam.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmPostParam)
        QtCore.QMetaObject.connectSlotsByName(frmPostParam)
        frmPostParam.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmPostParam):
        _translate = QtCore.QCoreApplication.translate
        frmPostParam.setWindowTitle(_translate("frmPostParam", "显示参数"))
        self.btnOK.setText(_translate("frmPostParam", "确定"))
        self.btnCancel.setText(_translate("frmPostParam", "取消"))
        self.gbxDomain.setTitle(_translate("frmPostParam", "图形设置"))
        self.chk1.setText(_translate("frmPostParam", "显示模型"))
        self.chk2.setText(_translate("frmPostParam", "显示分析结果"))
