# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmTime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmTime(object):
    def setupUi(self, frmTime):
        frmTime.setObjectName("frmTime")
        frmTime.resize(345, 379)
        font = QtGui.QFont()
        font.setPointSize(9)
        frmTime.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmTime)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(70, 340, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(190, 340, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 111, 30))
        self.label_4.setObjectName("label_4")
        self.txtTimeTotal_g = QtWidgets.QLineEdit(self.groupBox)
        self.txtTimeTotal_g.setGeometry(QtCore.QRect(140, 20, 160, 30))
        self.txtTimeTotal_g.setObjectName("txtTimeTotal_g")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 111, 30))
        self.label_5.setObjectName("label_5")
        self.txtTimeStep_g = QtWidgets.QLineEdit(self.groupBox)
        self.txtTimeStep_g.setGeometry(QtCore.QRect(140, 60, 160, 30))
        self.txtTimeStep_g.setObjectName("txtTimeStep_g")
        self.btnAddRow = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddRow.setGeometry(QtCore.QRect(10, 300, 101, 26))
        self.btnAddRow.setObjectName("btnAddRow")
        self.btnRemoveRow = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoveRow.setGeometry(QtCore.QRect(230, 300, 101, 26))
        self.btnRemoveRow.setObjectName("btnRemoveRow")
        self.tbPoints = QtWidgets.QTableWidget(self.centralwidget)
        self.tbPoints.setGeometry(QtCore.QRect(10, 120, 321, 171))
        self.tbPoints.setObjectName("tbPoints")
        self.tbPoints.setColumnCount(1)
        self.tbPoints.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbPoints.setHorizontalHeaderItem(0, item)
        frmTime.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmTime)
        QtCore.QMetaObject.connectSlotsByName(frmTime)
        frmTime.setTabOrder(self.txtTimeTotal_g, self.txtTimeStep_g)
        frmTime.setTabOrder(self.txtTimeStep_g, self.btnOK)
        frmTime.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmTime):
        _translate = QtCore.QCoreApplication.translate
        frmTime.setWindowTitle(_translate("frmTime", "仿真时间设置"))
        self.btnOK.setText(_translate("frmTime", "确定"))
        self.btnCancel.setText(_translate("frmTime", "取消"))
        self.label_4.setText(_translate("frmTime", "总仿真时间"))
        self.txtTimeTotal_g.setText(_translate("frmTime", "1"))
        self.label_5.setText(_translate("frmTime", "时间步长"))
        self.txtTimeStep_g.setText(_translate("frmTime", "1"))
        self.btnAddRow.setText(_translate("frmTime", "添加时刻"))
        self.btnRemoveRow.setText(_translate("frmTime", "移除选中行"))
        item = self.tbPoints.horizontalHeaderItem(0)
        item.setText(_translate("frmTime", "特定观察时刻(s)"))
