# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmSimulation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmSimulation(object):
    def setupUi(self, frmSimulation):
        frmSimulation.setObjectName("frmSimulation")
        frmSimulation.setWindowModality(QtCore.Qt.WindowModal)
        frmSimulation.resize(320, 240)
        self.centralwidget = QtWidgets.QWidget(frmSimulation)
        self.centralwidget.setObjectName("centralwidget")
        self.lblProject = QtWidgets.QLabel(self.centralwidget)
        self.lblProject.setGeometry(QtCore.QRect(30, 50, 41, 16))
        self.lblProject.setObjectName("lblProject")
        self.lblSimulation = QtWidgets.QLabel(self.centralwidget)
        self.lblSimulation.setGeometry(QtCore.QRect(30, 100, 41, 9))
        self.lblSimulation.setObjectName("lblSimulation")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 50, 161, 16))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 100, 161, 16))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btnRun = QtWidgets.QPushButton(self.centralwidget)
        self.btnRun.setGeometry(QtCore.QRect(200, 160, 56, 17))
        self.btnRun.setObjectName("btnRun")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(260, 50, 21, 16))
        self.btnBrowse.setObjectName("btnBrowse")
        frmSimulation.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmSimulation)
        QtCore.QMetaObject.connectSlotsByName(frmSimulation)

    def retranslateUi(self, frmSimulation):
        _translate = QtCore.QCoreApplication.translate
        frmSimulation.setWindowTitle(_translate("frmSimulation", "Start Simulation"))
        self.lblProject.setText(_translate("frmSimulation", "项目"))
        self.lblSimulation.setText(_translate("frmSimulation", "算法程序"))
        self.btnRun.setText(_translate("frmSimulation", "Run"))
        self.btnBrowse.setText(_translate("frmSimulation", "..."))
