# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmPoints.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMediaModify(object):
    def setupUi(self, frmMediaModify):
        frmMediaModify.setObjectName("frmMediaModify")
        frmMediaModify.resize(632, 684)
        self.centralwidget = QtWidgets.QWidget(frmMediaModify)
        self.centralwidget.setObjectName("centralwidget")
        self.groupModel = QtWidgets.QGroupBox(self.centralwidget)
        self.groupModel.setGeometry(QtCore.QRect(10, 20, 611, 651))
        self.groupModel.setObjectName("groupModel")
        self.txtMediaName = QtWidgets.QLineEdit(self.groupModel)
        self.txtMediaName.setGeometry(QtCore.QRect(170, 40, 421, 30))
        self.txtMediaName.setObjectName("txtMediaName")
        self.label = QtWidgets.QLabel(self.groupModel)
        self.label.setGeometry(QtCore.QRect(20, 40, 141, 30))
        self.label.setObjectName("label")
        self.btnApply = QtWidgets.QPushButton(self.groupModel)
        self.btnApply.setGeometry(QtCore.QRect(130, 610, 151, 30))
        self.btnApply.setObjectName("btnApply")
        self.groupBox = QtWidgets.QGroupBox(self.groupModel)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 591, 501))
        self.groupBox.setObjectName("groupBox")
        self.btnAddFreq = QtWidgets.QPushButton(self.groupBox)
        self.btnAddFreq.setGeometry(QtCore.QRect(10, 460, 261, 30))
        self.btnAddFreq.setObjectName("btnAddFreq")
        self.btnRemoveFreq = QtWidgets.QPushButton(self.groupBox)
        self.btnRemoveFreq.setGeometry(QtCore.QRect(320, 460, 261, 30))
        self.btnRemoveFreq.setObjectName("btnRemoveFreq")
        self.tbFreqList = QtWidgets.QTableWidget(self.groupBox)
        self.tbFreqList.setGeometry(QtCore.QRect(10, 30, 571, 421))
        self.tbFreqList.setObjectName("tbFreqList")
        self.tbFreqList.setColumnCount(0)
        self.tbFreqList.setRowCount(0)
        self.btnOK = QtWidgets.QPushButton(self.groupModel)
        self.btnOK.setGeometry(QtCore.QRect(330, 610, 151, 30))
        self.btnOK.setObjectName("btnOK")
        frmMediaModify.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMediaModify)
        QtCore.QMetaObject.connectSlotsByName(frmMediaModify)

    def retranslateUi(self, frmMediaModify):
        _translate = QtCore.QCoreApplication.translate
        frmMediaModify.setWindowTitle(_translate("frmMediaModify", "Media modify"))
        self.groupModel.setTitle(_translate("frmMediaModify", "Delectric modeling"))
        self.label.setText(_translate("frmMediaModify", "Medium name"))
        self.btnApply.setText(_translate("frmMediaModify", "Apply"))
        self.groupBox.setTitle(_translate("frmMediaModify", "Frequency list"))
        self.btnAddFreq.setText(_translate("frmMediaModify", "Add Frequency"))
        self.btnRemoveFreq.setText(_translate("frmMediaModify", "Remove Frequency"))
        self.btnOK.setText(_translate("frmMediaModify", "OK"))
