# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmThermalConvection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmThermalConvection(object):
    def setupUi(self, frmThermalConvection):
        frmThermalConvection.setObjectName("frmThermalConvection")
        frmThermalConvection.resize(308, 129)
        self.centralwidget = QtWidgets.QWidget(frmThermalConvection)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(190, 80, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(50, 80, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 60, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtValue = QtWidgets.QLineEdit(self.centralwidget)
        self.txtValue.setGeometry(QtCore.QRect(90, 30, 181, 30))
        self.txtValue.setObjectName("txtValue")
        frmThermalConvection.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmThermalConvection)
        QtCore.QMetaObject.connectSlotsByName(frmThermalConvection)

    def retranslateUi(self, frmThermalConvection):
        _translate = QtCore.QCoreApplication.translate
        frmThermalConvection.setWindowTitle(_translate("frmThermalConvection", "对流设置"))
        self.btnCancel.setText(_translate("frmThermalConvection", "取消"))
        self.btnOK.setText(_translate("frmThermalConvection", "确定"))
        self.label_3.setText(_translate("frmThermalConvection", "对流系数"))
