# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmThermalDirichlet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmThermalDirichlet(object):
    def setupUi(self, frmThermalDirichlet):
        frmThermalDirichlet.setObjectName("frmThermalDirichlet")
        frmThermalDirichlet.resize(308, 192)
        self.centralwidget = QtWidgets.QWidget(frmThermalDirichlet)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(110, 140, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 140, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 140, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.lblValue = QtWidgets.QLabel(self.centralwidget)
        self.lblValue.setGeometry(QtCore.QRect(20, 70, 81, 30))
        self.lblValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblValue.setObjectName("lblValue")
        self.lblSelect = QtWidgets.QLabel(self.centralwidget)
        self.lblSelect.setGeometry(QtCore.QRect(20, 30, 81, 30))
        self.lblSelect.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSelect.setObjectName("lblSelect")
        self.txtValue = QtWidgets.QLineEdit(self.centralwidget)
        self.txtValue.setGeometry(QtCore.QRect(110, 70, 161, 30))
        self.txtValue.setObjectName("txtValue")
        self.txtSelectId = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSelectId.setGeometry(QtCore.QRect(110, 30, 161, 30))
        self.txtSelectId.setObjectName("txtSelectId")
        frmThermalDirichlet.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmThermalDirichlet)
        QtCore.QMetaObject.connectSlotsByName(frmThermalDirichlet)

    def retranslateUi(self, frmThermalDirichlet):
        _translate = QtCore.QCoreApplication.translate
        frmThermalDirichlet.setWindowTitle(_translate("frmThermalDirichlet", "热-固定温度"))
        self.btnApply.setText(_translate("frmThermalDirichlet", "应用"))
        self.btnCancel.setText(_translate("frmThermalDirichlet", "取消"))
        self.btnOK.setText(_translate("frmThermalDirichlet", "确定"))
        self.lblValue.setText(_translate("frmThermalDirichlet", "温度"))
        self.lblSelect.setText(_translate("frmThermalDirichlet", "面编号"))
