# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmOpacity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmOpacity(object):
    def setupUi(self, frmOpacity):
        frmOpacity.setObjectName("frmOpacity")
        frmOpacity.resize(350, 176)
        self.centralwidget = QtWidgets.QWidget(frmOpacity)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(30, 130, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(250, 130, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(140, 130, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.gbxOpacity = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxOpacity.setGeometry(QtCore.QRect(20, 10, 311, 111))
        self.gbxOpacity.setObjectName("gbxOpacity")
        self.txtMaxSize = QtWidgets.QLineEdit(self.gbxOpacity)
        self.txtMaxSize.setGeometry(QtCore.QRect(140, 30, 141, 30))
        self.txtMaxSize.setObjectName("txtMaxSize")
        self.label = QtWidgets.QLabel(self.gbxOpacity)
        self.label.setGeometry(QtCore.QRect(10, 30, 121, 30))
        self.label.setObjectName("label")
        self.txtOpacityMap = QtWidgets.QLineEdit(self.gbxOpacity)
        self.txtOpacityMap.setGeometry(QtCore.QRect(140, 70, 141, 30))
        self.txtOpacityMap.setObjectName("txtOpacityMap")
        self.label_2 = QtWidgets.QLabel(self.gbxOpacity)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 121, 30))
        self.label_2.setObjectName("label_2")
        frmOpacity.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmOpacity)
        QtCore.QMetaObject.connectSlotsByName(frmOpacity)

    def retranslateUi(self, frmOpacity):
        _translate = QtCore.QCoreApplication.translate
        frmOpacity.setWindowTitle(_translate("frmOpacity", "透明度设置"))
        self.btnOK.setText(_translate("frmOpacity", "确定"))
        self.btnCancel.setText(_translate("frmOpacity", "取消"))
        self.btnApply.setText(_translate("frmOpacity", "应用"))
        self.gbxOpacity.setTitle(_translate("frmOpacity", "透明度(0~1)"))
        self.label.setText(_translate("frmOpacity", "几何模型"))
        self.label_2.setText(_translate("frmOpacity", "云图"))
