# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmEMPEC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmEMPEC(object):
    def setupUi(self, frmEMPEC):
        frmEMPEC.setObjectName("frmEMPEC")
        frmEMPEC.resize(308, 149)
        self.centralwidget = QtWidgets.QWidget(frmEMPEC)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(110, 90, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 90, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 90, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.txtFaceId = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFaceId.setGeometry(QtCore.QRect(90, 30, 191, 30))
        self.txtFaceId.setObjectName("txtFaceId")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        frmEMPEC.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmEMPEC)
        QtCore.QMetaObject.connectSlotsByName(frmEMPEC)

    def retranslateUi(self, frmEMPEC):
        _translate = QtCore.QCoreApplication.translate
        frmEMPEC.setWindowTitle(_translate("frmEMPEC", "电磁-PEC"))
        self.btnApply.setText(_translate("frmEMPEC", "应用"))
        self.btnCancel.setText(_translate("frmEMPEC", "取消"))
        self.btnOK.setText(_translate("frmEMPEC", "确定"))
        self.label.setText(_translate("frmEMPEC", "面编号"))
