# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmDoppingAnalysis copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmDoppingAnalysis(object):
    def setupUi(self, frmDoppingAnalysis):
        frmDoppingAnalysis.setObjectName("frmDoppingAnalysis")
        frmDoppingAnalysis.resize(329, 204)
        self.centralwidget = QtWidgets.QWidget(frmDoppingAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(120, 160, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(220, 160, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 160, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.groupCondition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCondition.setGeometry(QtCore.QRect(10, 20, 301, 131))
        self.groupCondition.setTitle("")
        self.groupCondition.setObjectName("groupCondition")
        self.txtBodyId = QtWidgets.QLineEdit(self.groupCondition)
        self.txtBodyId.setGeometry(QtCore.QRect(100, 10, 171, 30))
        self.txtBodyId.setObjectName("txtBodyId")
        self.label = QtWidgets.QLabel(self.groupCondition)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupCondition)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 81, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtConc = QtWidgets.QLineEdit(self.groupCondition)
        self.txtConc.setGeometry(QtCore.QRect(100, 90, 171, 30))
        self.txtConc.setObjectName("txtConc")
        self.cbxDoppingType = QtWidgets.QComboBox(self.groupCondition)
        self.cbxDoppingType.setGeometry(QtCore.QRect(100, 50, 171, 30))
        self.cbxDoppingType.setObjectName("cbxDoppingType")
        self.cbxDoppingType.addItem("")
        self.cbxDoppingType.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupCondition)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 81, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        frmDoppingAnalysis.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmDoppingAnalysis)
        QtCore.QMetaObject.connectSlotsByName(frmDoppingAnalysis)

    def retranslateUi(self, frmDoppingAnalysis):
        _translate = QtCore.QCoreApplication.translate
        frmDoppingAnalysis.setWindowTitle(_translate("frmDoppingAnalysis", "解析掺杂"))
        self.btnApply.setText(_translate("frmDoppingAnalysis", "应用"))
        self.btnCancel.setText(_translate("frmDoppingAnalysis", "取消"))
        self.btnOK.setText(_translate("frmDoppingAnalysis", "确定"))
        self.label.setText(_translate("frmDoppingAnalysis", "体编号"))
        self.label_3.setText(_translate("frmDoppingAnalysis", "杂质浓度(1/m³)"))
        self.cbxDoppingType.setItemText(0, _translate("frmDoppingAnalysis", "施主掺杂"))
        self.cbxDoppingType.setItemText(1, _translate("frmDoppingAnalysis", "受主掺杂"))
        self.label_5.setText(_translate("frmDoppingAnalysis", "杂质类型"))
