# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmTemperature.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmTemperature(object):
    def setupUi(self, frmTemperature):
        frmTemperature.setObjectName("frmTemperature")
        frmTemperature.resize(337, 167)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTemperature.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmTemperature)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(70, 120, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(190, 120, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.txtTemperatureEnv = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTemperatureEnv.setGeometry(QtCore.QRect(140, 70, 160, 30))
        self.txtTemperatureEnv.setObjectName("txtTemperatureEnv")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 111, 30))
        self.label_5.setObjectName("label_5")
        self.txtTemperatureStart = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTemperatureStart.setGeometry(QtCore.QRect(140, 20, 160, 30))
        self.txtTemperatureStart.setObjectName("txtTemperatureStart")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 111, 30))
        self.label_4.setObjectName("label_4")
        frmTemperature.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmTemperature)
        QtCore.QMetaObject.connectSlotsByName(frmTemperature)
        frmTemperature.setTabOrder(self.txtTemperatureStart, self.txtTemperatureEnv)
        frmTemperature.setTabOrder(self.txtTemperatureEnv, self.btnOK)
        frmTemperature.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmTemperature):
        _translate = QtCore.QCoreApplication.translate
        frmTemperature.setWindowTitle(_translate("frmTemperature", "温度设置"))
        self.btnOK.setText(_translate("frmTemperature", "确定"))
        self.btnCancel.setText(_translate("frmTemperature", "取消"))
        self.txtTemperatureEnv.setText(_translate("frmTemperature", "1"))
        self.label_5.setText(_translate("frmTemperature", "环境温度(K)"))
        self.txtTemperatureStart.setText(_translate("frmTemperature", "1"))
        self.label_4.setText(_translate("frmTemperature", "初始温度(K)"))
