# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmTime copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmTime(object):
    def setupUi(self, frmTime):
        frmTime.setObjectName("frmTime")
        frmTime.resize(337, 173)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTime.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmTime)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(70, 130, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(190, 130, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.txtTimeStepFactor = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTimeStepFactor.setGeometry(QtCore.QRect(140, 80, 160, 25))
        self.txtTimeStepFactor.setObjectName("txtTimeStepFactor")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 111, 25))
        self.label_6.setObjectName("label_6")
        self.txtTimeStepNum = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTimeStepNum.setGeometry(QtCore.QRect(140, 50, 160, 25))
        self.txtTimeStepNum.setObjectName("txtTimeStepNum")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 111, 25))
        self.label_5.setObjectName("label_5")
        self.txtTimeStep = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTimeStep.setGeometry(QtCore.QRect(140, 20, 160, 25))
        self.txtTimeStep.setObjectName("txtTimeStep")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 111, 25))
        self.label_4.setObjectName("label_4")
        frmTime.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmTime)
        QtCore.QMetaObject.connectSlotsByName(frmTime)
        frmTime.setTabOrder(self.txtTimeStep, self.txtTimeStepNum)
        frmTime.setTabOrder(self.txtTimeStepNum, self.txtTimeStepFactor)
        frmTime.setTabOrder(self.txtTimeStepFactor, self.btnOK)
        frmTime.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmTime):
        _translate = QtCore.QCoreApplication.translate
        frmTime.setWindowTitle(_translate("frmTime", "时间设置"))
        self.btnOK.setText(_translate("frmTime", "确定"))
        self.btnCancel.setText(_translate("frmTime", "取消"))
        self.txtTimeStepFactor.setText(_translate("frmTime", "1"))
        self.label_6.setText(_translate("frmTime", "比例因子"))
        self.txtTimeStepNum.setText(_translate("frmTime", "1"))
        self.label_5.setText(_translate("frmTime", "时间步数"))
        self.txtTimeStep.setText(_translate("frmTime", "1"))
        self.label_4.setText(_translate("frmTime", "时间步长"))
