# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmMPI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMPI(object):
    def setupUi(self, frmMPI):
        frmMPI.setObjectName("frmMPI")
        frmMPI.resize(283, 132)
        font = QtGui.QFont()
        font.setPointSize(12)
        frmMPI.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmMPI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 81, 25))
        self.label.setObjectName("label")
        self.txtMPINum = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMPINum.setGeometry(QtCore.QRect(130, 30, 121, 25))
        self.txtMPINum.setObjectName("txtMPINum")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(30, 80, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(170, 80, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 231, 25))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        frmMPI.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMPI)
        QtCore.QMetaObject.connectSlotsByName(frmMPI)

    def retranslateUi(self, frmMPI):
        _translate = QtCore.QCoreApplication.translate
        frmMPI.setWindowTitle(_translate("frmMPI", "并行计算设置"))
        self.label.setText(_translate("frmMPI", "并行核数"))
        self.btnOK.setText(_translate("frmMPI", "确定"))
        self.btnCancel.setText(_translate("frmMPI", "取消"))
