# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmMediaIsotropic copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMediaIsotropic(object):
    def setupUi(self, frmMediaIsotropic):
        frmMediaIsotropic.setObjectName("frmMediaIsotropic")
        frmMediaIsotropic.resize(284, 288)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMediaIsotropic.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmMediaIsotropic)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 28))
        self.label.setObjectName("label")
        self.txtMediaName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMediaName.setGeometry(QtCore.QRect(110, 20, 160, 28))
        self.txtMediaName.setObjectName("txtMediaName")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(160, 240, 80, 30))
        self.btnClose.setObjectName("btnClose")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(40, 240, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.txtPermittivity = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPermittivity.setGeometry(QtCore.QRect(110, 55, 160, 28))
        self.txtPermittivity.setObjectName("txtPermittivity")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 55, 91, 28))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 28))
        self.label_3.setObjectName("label_3")
        self.txtPermeability = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPermeability.setGeometry(QtCore.QRect(110, 90, 160, 28))
        self.txtPermeability.setObjectName("txtPermeability")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 125, 91, 28))
        self.label_4.setObjectName("label_4")
        self.txtEConductivity = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEConductivity.setGeometry(QtCore.QRect(110, 125, 160, 28))
        self.txtEConductivity.setObjectName("txtEConductivity")
        self.txtDF = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDF.setGeometry(QtCore.QRect(110, 160, 160, 28))
        self.txtDF.setObjectName("txtDF")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 91, 28))
        self.label_5.setObjectName("label_5")
        self.txtMF = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMF.setGeometry(QtCore.QRect(110, 195, 160, 28))
        self.txtMF.setObjectName("txtMF")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 195, 91, 28))
        self.label_6.setObjectName("label_6")
        frmMediaIsotropic.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMediaIsotropic)
        QtCore.QMetaObject.connectSlotsByName(frmMediaIsotropic)

    def retranslateUi(self, frmMediaIsotropic):
        _translate = QtCore.QCoreApplication.translate
        frmMediaIsotropic.setWindowTitle(_translate("frmMediaIsotropic", "材料"))
        self.label.setText(_translate("frmMediaIsotropic", "材料名称"))
        self.btnClose.setText(_translate("frmMediaIsotropic", "取消"))
        self.btnOK.setText(_translate("frmMediaIsotropic", "确定"))
        self.label_2.setText(_translate("frmMediaIsotropic", "介电常数"))
        self.label_3.setText(_translate("frmMediaIsotropic", "磁导率"))
        self.label_4.setText(_translate("frmMediaIsotropic", "电导率"))
        self.label_5.setText(_translate("frmMediaIsotropic", "电损耗角正切"))
        self.label_6.setText(_translate("frmMediaIsotropic", "磁损耗角正切"))
