# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmFilterPointsSEMI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmFilterPointsSEMI(object):
    def setupUi(self, frmFilterPointsSEMI):
        frmFilterPointsSEMI.setObjectName("frmFilterPointsSEMI")
        frmFilterPointsSEMI.resize(315, 171)
        self.centralwidget = QtWidgets.QWidget(frmFilterPointsSEMI)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 130, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(180, 130, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxDomainPF = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxDomainPF.setGeometry(QtCore.QRect(10, 10, 291, 91))
        self.gbxDomainPF.setTitle("")
        self.gbxDomainPF.setObjectName("gbxDomainPF")
        self.label_2 = QtWidgets.QLabel(self.gbxDomainPF)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 71, 28))
        self.label_2.setObjectName("label_2")
        self.cbxValues = QtWidgets.QComboBox(self.gbxDomainPF)
        self.cbxValues.setGeometry(QtCore.QRect(100, 30, 161, 28))
        self.cbxValues.setObjectName("cbxValues")
        frmFilterPointsSEMI.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmFilterPointsSEMI)
        QtCore.QMetaObject.connectSlotsByName(frmFilterPointsSEMI)
        frmFilterPointsSEMI.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmFilterPointsSEMI):
        _translate = QtCore.QCoreApplication.translate
        frmFilterPointsSEMI.setWindowTitle(_translate("frmFilterPointsSEMI", "观察点物理量"))
        self.btnOK.setText(_translate("frmFilterPointsSEMI", "确定"))
        self.btnCancel.setText(_translate("frmFilterPointsSEMI", "取消"))
        self.label_2.setText(_translate("frmFilterPointsSEMI", "物理量"))
