# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmDomainPF.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmDomainPF(object):
    def setupUi(self, frmDomainPF):
        frmDomainPF.setObjectName("frmDomainPF")
        frmDomainPF.resize(323, 240)
        self.centralwidget = QtWidgets.QWidget(frmDomainPF)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 190, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(180, 190, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxDomainPF = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxDomainPF.setGeometry(QtCore.QRect(10, 10, 301, 161))
        self.gbxDomainPF.setObjectName("gbxDomainPF")
        self.chkModel = QtWidgets.QCheckBox(self.gbxDomainPF)
        self.chkModel.setGeometry(QtCore.QRect(60, 30, 141, 30))
        self.chkModel.setObjectName("chkModel")
        self.chkAir = QtWidgets.QCheckBox(self.gbxDomainPF)
        self.chkAir.setGeometry(QtCore.QRect(60, 70, 141, 30))
        self.chkAir.setObjectName("chkAir")
        self.chkPML = QtWidgets.QCheckBox(self.gbxDomainPF)
        self.chkPML.setGeometry(QtCore.QRect(60, 110, 141, 30))
        self.chkPML.setObjectName("chkPML")
        frmDomainPF.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmDomainPF)
        QtCore.QMetaObject.connectSlotsByName(frmDomainPF)
        frmDomainPF.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmDomainPF):
        _translate = QtCore.QCoreApplication.translate
        frmDomainPF.setWindowTitle(_translate("frmDomainPF", "物理场"))
        self.btnOK.setText(_translate("frmDomainPF", "确定"))
        self.btnCancel.setText(_translate("frmDomainPF", "取消"))
        self.gbxDomainPF.setTitle(_translate("frmDomainPF", "求解域设置"))
        self.chkModel.setText(_translate("frmDomainPF", "模型域"))
        self.chkAir.setText(_translate("frmDomainPF", "空气域"))
        self.chkPML.setText(_translate("frmDomainPF", "完美匹配层"))
