# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmETimes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmETimes(object):
    def setupUi(self, frmETimes):
        frmETimes.setObjectName("frmETimes")
        frmETimes.resize(308, 149)
        self.centralwidget = QtWidgets.QWidget(frmETimes)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(110, 90, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 90, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 90, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.txtETimes = QtWidgets.QLineEdit(self.centralwidget)
        self.txtETimes.setGeometry(QtCore.QRect(90, 30, 191, 30))
        self.txtETimes.setObjectName("txtETimes")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        frmETimes.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmETimes)
        QtCore.QMetaObject.connectSlotsByName(frmETimes)

    def retranslateUi(self, frmETimes):
        _translate = QtCore.QCoreApplication.translate
        frmETimes.setWindowTitle(_translate("frmETimes", "迭代电势"))
        self.btnApply.setText(_translate("frmETimes", "应用"))
        self.btnCancel.setText(_translate("frmETimes", "取消"))
        self.btnOK.setText(_translate("frmETimes", "确定"))
        self.label.setText(_translate("frmETimes", "迭代次数"))
