# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmDoppingGauss.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmDoppingGauss(object):
    def setupUi(self, frmDoppingGauss):
        frmDoppingGauss.setObjectName("frmDoppingGauss")
        frmDoppingGauss.resize(347, 291)
        self.centralwidget = QtWidgets.QWidget(frmDoppingGauss)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(120, 250, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(220, 250, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 250, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.groupCondition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCondition.setGeometry(QtCore.QRect(10, 20, 301, 221))
        self.groupCondition.setTitle("")
        self.groupCondition.setObjectName("groupCondition")
        self.txtBodyId = QtWidgets.QLineEdit(self.groupCondition)
        self.txtBodyId.setGeometry(QtCore.QRect(110, 10, 171, 30))
        self.txtBodyId.setObjectName("txtBodyId")
        self.label = QtWidgets.QLabel(self.groupCondition)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupCondition)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 91, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtConc = QtWidgets.QLineEdit(self.groupCondition)
        self.txtConc.setGeometry(QtCore.QRect(110, 130, 171, 30))
        self.txtConc.setObjectName("txtConc")
        self.txtFaceId = QtWidgets.QLineEdit(self.groupCondition)
        self.txtFaceId.setGeometry(QtCore.QRect(110, 50, 171, 30))
        self.txtFaceId.setObjectName("txtFaceId")
        self.label_4 = QtWidgets.QLabel(self.groupCondition)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 91, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.cbxDoppingType = QtWidgets.QComboBox(self.groupCondition)
        self.cbxDoppingType.setGeometry(QtCore.QRect(110, 90, 171, 30))
        self.cbxDoppingType.setObjectName("cbxDoppingType")
        self.cbxDoppingType.addItem("")
        self.cbxDoppingType.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupCondition)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 91, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupCondition)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 91, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.txtDepth = QtWidgets.QLineEdit(self.groupCondition)
        self.txtDepth.setGeometry(QtCore.QRect(110, 170, 171, 30))
        self.txtDepth.setText("")
        self.txtDepth.setObjectName("txtDepth")
        frmDoppingGauss.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmDoppingGauss)
        QtCore.QMetaObject.connectSlotsByName(frmDoppingGauss)

    def retranslateUi(self, frmDoppingGauss):
        _translate = QtCore.QCoreApplication.translate
        frmDoppingGauss.setWindowTitle(_translate("frmDoppingGauss", "高斯掺杂"))
        self.btnApply.setText(_translate("frmDoppingGauss", "应用"))
        self.btnCancel.setText(_translate("frmDoppingGauss", "取消"))
        self.btnOK.setText(_translate("frmDoppingGauss", "确定"))
        self.label.setText(_translate("frmDoppingGauss", "体编号"))
        self.label_3.setText(_translate("frmDoppingGauss", "杂质浓度(1/m³)"))
        self.label_4.setText(_translate("frmDoppingGauss", "面编号"))
        self.cbxDoppingType.setItemText(0, _translate("frmDoppingGauss", "施主掺杂"))
        self.cbxDoppingType.setItemText(1, _translate("frmDoppingGauss", "受主掺杂"))
        self.label_5.setText(_translate("frmDoppingGauss", "掺杂类型"))
        self.label_6.setText(_translate("frmDoppingGauss", "衰减结深(m)"))
