# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmLicense.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmLicense(object):
    def setupUi(self, frmLicense):
        frmLicense.setObjectName("frmLicense")
        frmLicense.resize(556, 281)
        self.centralwidget = QtWidgets.QWidget(frmLicense)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(5, 40, 81, 30))
        self.label.setObjectName("label")
        self.txtPower = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPower.setGeometry(QtCore.QRect(120, 40, 321, 30))
        self.txtPower.setObjectName("txtPower")
        self.btnRegister = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegister.setGeometry(QtCore.QRect(170, 210, 80, 30))
        self.btnRegister.setObjectName("btnRegister")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(300, 210, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 120, 111, 30))
        self.label_2.setObjectName("label_2")
        self.txtLicense = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLicense.setGeometry(QtCore.QRect(120, 120, 321, 30))
        self.txtLicense.setObjectName("txtLicense")
        self.btnBrowser = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowser.setGeometry(QtCore.QRect(450, 120, 101, 30))
        self.btnBrowser.setObjectName("btnBrowser")
        frmLicense.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmLicense)
        QtCore.QMetaObject.connectSlotsByName(frmLicense)

    def retranslateUi(self, frmLicense):
        _translate = QtCore.QCoreApplication.translate
        frmLicense.setWindowTitle(_translate("frmLicense", "License Management"))
        self.label.setText(_translate("frmLicense", "Host ID"))
        self.btnRegister.setText(_translate("frmLicense", "Register"))
        self.btnCancel.setText(_translate("frmLicense", "Cancel"))
        self.label_2.setText(_translate("frmLicense", "License code"))
        self.btnBrowser.setText(_translate("frmLicense", "license..."))
