# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmAntennaPoints.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmAntennaPoints(object):
    def setupUi(self, frmAntennaPoints):
        frmAntennaPoints.setObjectName("frmAntennaPoints")
        frmAntennaPoints.resize(459, 585)
        self.centralwidget = QtWidgets.QWidget(frmAntennaPoints)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 441, 501))
        self.groupBox.setObjectName("groupBox")
        self.btnAddFreq = QtWidgets.QPushButton(self.groupBox)
        self.btnAddFreq.setGeometry(QtCore.QRect(10, 460, 191, 30))
        self.btnAddFreq.setObjectName("btnAddFreq")
        self.btnRemoveFreq = QtWidgets.QPushButton(self.groupBox)
        self.btnRemoveFreq.setGeometry(QtCore.QRect(230, 460, 201, 30))
        self.btnRemoveFreq.setObjectName("btnRemoveFreq")
        self.tbPoints = QtWidgets.QTableWidget(self.groupBox)
        self.tbPoints.setGeometry(QtCore.QRect(10, 30, 421, 421))
        self.tbPoints.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tbPoints.setObjectName("tbPoints")
        self.tbPoints.setColumnCount(0)
        self.tbPoints.setRowCount(0)
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(60, 540, 151, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(240, 540, 151, 30))
        self.btnOK.setObjectName("btnOK")
        frmAntennaPoints.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmAntennaPoints)
        QtCore.QMetaObject.connectSlotsByName(frmAntennaPoints)

    def retranslateUi(self, frmAntennaPoints):
        _translate = QtCore.QCoreApplication.translate
        frmAntennaPoints.setWindowTitle(_translate("frmAntennaPoints", "Antenna input points"))
        self.groupBox.setTitle(_translate("frmAntennaPoints", "Anntenna points"))
        self.btnAddFreq.setText(_translate("frmAntennaPoints", "Add Point"))
        self.btnRemoveFreq.setText(_translate("frmAntennaPoints", "Remove Point"))
        self.btnApply.setText(_translate("frmAntennaPoints", "Apply"))
        self.btnOK.setText(_translate("frmAntennaPoints", "OK"))
