# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmNewProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmProject(object):
    def setupUi(self, frmProject):
        frmProject.setObjectName("frmProject")
        frmProject.setWindowModality(QtCore.Qt.WindowModal)
        frmProject.resize(564, 395)
        self.lblProjectName = QtWidgets.QLabel(frmProject)
        self.lblProjectName.setGeometry(QtCore.QRect(100, 100, 41, 20))
        self.lblProjectName.setObjectName("lblProjectName")
        self.txtProjectName = QtWidgets.QLineEdit(frmProject)
        self.txtProjectName.setGeometry(QtCore.QRect(150, 100, 201, 21))
        self.txtProjectName.setObjectName("txtProjectName")
        self.lblProjectDir = QtWidgets.QLabel(frmProject)
        self.lblProjectDir.setGeometry(QtCore.QRect(100, 170, 41, 20))
        self.lblProjectDir.setObjectName("lblProjectDir")
        self.lineEdit = QtWidgets.QLineEdit(frmProject)
        self.lineEdit.setGeometry(QtCore.QRect(150, 170, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.btnBrowse = QtWidgets.QPushButton(frmProject)
        self.btnBrowse.setGeometry(QtCore.QRect(360, 170, 51, 21))
        self.btnBrowse.setObjectName("btnBrowse")
        self.btnCreate = QtWidgets.QPushButton(frmProject)
        self.btnCreate.setGeometry(QtCore.QRect(220, 280, 61, 21))
        self.btnCreate.setObjectName("btnCreate")

        self.retranslateUi(frmProject)
        QtCore.QMetaObject.connectSlotsByName(frmProject)

    def retranslateUi(self, frmProject):
        _translate = QtCore.QCoreApplication.translate
        frmProject.setWindowTitle(_translate("frmProject", "配置新项目"))
        self.lblProjectName.setText(_translate("frmProject", "项目名称"))
        self.txtProjectName.setText(_translate("frmProject", "ProjectDefault"))
        self.lblProjectDir.setText(_translate("frmProject", "项目位置"))
        self.btnBrowse.setText(_translate("frmProject", "..."))
        self.btnCreate.setText(_translate("frmProject", "创建"))
