# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmTime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmTime(object):
    def setupUi(self, frmTime):
        frmTime.setObjectName("frmTime")
        frmTime.resize(343, 271)
        font = QtGui.QFont()
        font.setPointSize(9)
        frmTime.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmTime)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(70, 230, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(190, 230, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 101))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 111, 30))
        self.label_4.setObjectName("label_4")
        self.txtTimeStep = QtWidgets.QLineEdit(self.groupBox)
        self.txtTimeStep.setGeometry(QtCore.QRect(140, 20, 160, 30))
        self.txtTimeStep.setObjectName("txtTimeStep")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 111, 30))
        self.label_5.setObjectName("label_5")
        self.txtTimeStepNum = QtWidgets.QLineEdit(self.groupBox)
        self.txtTimeStepNum.setGeometry(QtCore.QRect(140, 60, 160, 30))
        self.txtTimeStepNum.setObjectName("txtTimeStepNum")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 321, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 111, 30))
        self.label_8.setObjectName("label_8")
        self.txtTimeStep_heat = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtTimeStep_heat.setGeometry(QtCore.QRect(140, 20, 160, 30))
        self.txtTimeStep_heat.setObjectName("txtTimeStep_heat")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 111, 30))
        self.label_9.setObjectName("label_9")
        self.txtTimeStepNum_heat = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtTimeStepNum_heat.setGeometry(QtCore.QRect(140, 60, 160, 30))
        self.txtTimeStepNum_heat.setObjectName("txtTimeStepNum_heat")
        frmTime.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmTime)
        QtCore.QMetaObject.connectSlotsByName(frmTime)
        frmTime.setTabOrder(self.txtTimeStep, self.txtTimeStepNum)
        frmTime.setTabOrder(self.txtTimeStepNum, self.btnOK)
        frmTime.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmTime):
        _translate = QtCore.QCoreApplication.translate
        frmTime.setWindowTitle(_translate("frmTime", "时间设置"))
        self.btnOK.setText(_translate("frmTime", "确定"))
        self.btnCancel.setText(_translate("frmTime", "取消"))
        self.groupBox.setTitle(_translate("frmTime", "电磁"))
        self.label_4.setText(_translate("frmTime", "时间步长"))
        self.txtTimeStep.setText(_translate("frmTime", "1"))
        self.label_5.setText(_translate("frmTime", "时间步数"))
        self.txtTimeStepNum.setText(_translate("frmTime", "1"))
        self.groupBox_2.setTitle(_translate("frmTime", "热"))
        self.label_8.setText(_translate("frmTime", "时间步长"))
        self.txtTimeStep_heat.setText(_translate("frmTime", "1"))
        self.label_9.setText(_translate("frmTime", "时间步数"))
        self.txtTimeStepNum_heat.setText(_translate("frmTime", "1"))
