# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmScalar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmScalar(object):
    def setupUi(self, frmScalar):
        frmScalar.setObjectName("frmScalar")
        frmScalar.resize(389, 349)
        font = QtGui.QFont()
        font.setPointSize(9)
        frmScalar.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmScalar)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 371, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tabScaleRange = QtWidgets.QWidget()
        self.tabScaleRange.setObjectName("tabScaleRange")
        self.groupBox = QtWidgets.QGroupBox(self.tabScaleRange)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 341, 241))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 101, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 101, 25))
        self.label_3.setObjectName("label_3")
        self.txtMax = QtWidgets.QLineEdit(self.groupBox)
        self.txtMax.setEnabled(False)
        self.txtMax.setGeometry(QtCore.QRect(160, 150, 171, 25))
        self.txtMax.setObjectName("txtMax")
        self.txtMin = QtWidgets.QLineEdit(self.groupBox)
        self.txtMin.setEnabled(False)
        self.txtMin.setGeometry(QtCore.QRect(160, 110, 171, 25))
        self.txtMin.setObjectName("txtMin")
        self.rdbAuto = QtWidgets.QRadioButton(self.groupBox)
        self.rdbAuto.setGeometry(QtCore.QRect(10, 30, 401, 25))
        self.rdbAuto.setObjectName("rdbAuto")
        self.rdbFixed = QtWidgets.QRadioButton(self.groupBox)
        self.rdbFixed.setGeometry(QtCore.QRect(10, 60, 401, 25))
        self.rdbFixed.setObjectName("rdbFixed")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 141, 25))
        self.label_4.setObjectName("label_4")
        self.txtNumOfColors = QtWidgets.QLineEdit(self.groupBox)
        self.txtNumOfColors.setEnabled(True)
        self.txtNumOfColors.setGeometry(QtCore.QRect(160, 190, 171, 25))
        self.txtNumOfColors.setObjectName("txtNumOfColors")
        self.tabWidget.addTab(self.tabScaleRange, "")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(50, 310, 80, 25))
        self.btnOK.setObjectName("btnOK")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(140, 310, 80, 25))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(230, 310, 80, 25))
        self.btnCancel.setObjectName("btnCancel")
        frmScalar.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmScalar)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmScalar)

    def retranslateUi(self, frmScalar):
        _translate = QtCore.QCoreApplication.translate
        frmScalar.setWindowTitle(_translate("frmScalar", "云图颜色映射"))
        self.groupBox.setTitle(_translate("frmScalar", "线性映射"))
        self.label_2.setText(_translate("frmScalar", "最大值"))
        self.label_3.setText(_translate("frmScalar", "最小值"))
        self.rdbAuto.setText(_translate("frmScalar", "自动填充"))
        self.rdbFixed.setText(_translate("frmScalar", "固定值"))
        self.label_4.setText(_translate("frmScalar", "颜色数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabScaleRange), _translate("frmScalar", "颜色范围"))
        self.btnOK.setText(_translate("frmScalar", "确定"))
        self.btnApply.setText(_translate("frmScalar", "应用"))
        self.btnCancel.setText(_translate("frmScalar", "取消"))
