# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmFrequency - 副本.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmFrequency(object):
    def setupUi(self, frmFrequency):
        frmFrequency.setObjectName("frmFrequency")
        frmFrequency.resize(525, 416)
        self.centralwidget = QtWidgets.QWidget(frmFrequency)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 521, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 120, 171, 30))
        self.label.setObjectName("label")
        self.txtStart = QtWidgets.QLineEdit(self.tab)
        self.txtStart.setGeometry(QtCore.QRect(230, 120, 241, 30))
        self.txtStart.setObjectName("txtStart")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 171, 30))
        self.label_2.setObjectName("label_2")
        self.txtEnd = QtWidgets.QLineEdit(self.tab)
        self.txtEnd.setGeometry(QtCore.QRect(230, 170, 241, 30))
        self.txtEnd.setObjectName("txtEnd")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 171, 30))
        self.label_3.setObjectName("label_3")
        self.txtIncrement = QtWidgets.QLineEdit(self.tab)
        self.txtIncrement.setGeometry(QtCore.QRect(230, 220, 241, 30))
        self.txtIncrement.setObjectName("txtIncrement")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(230, 40, 241, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 201, 30))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(160, 360, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(270, 360, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        frmFrequency.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmFrequency)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFrequency)

    def retranslateUi(self, frmFrequency):
        _translate = QtCore.QCoreApplication.translate
        frmFrequency.setWindowTitle(_translate("frmFrequency", "Solution frequency"))
        self.label.setText(_translate("frmFrequency", "Start frequency(Hz)"))
        self.label_2.setText(_translate("frmFrequency", "End frequency(Hz)"))
        self.label_3.setText(_translate("frmFrequency", "Increcement(Hz)"))
        self.comboBox.setItemText(0, _translate("frmFrequency", "Sinosoid"))
        self.comboBox.setItemText(1, _translate("frmFrequency", "Blackman"))
        self.comboBox.setItemText(2, _translate("frmFrequency", "Chirp"))
        self.comboBox.setItemText(3, _translate("frmFrequency", "Gaussian"))
        self.comboBox.setItemText(4, _translate("frmFrequency", "Gaussian dirivative"))
        self.comboBox.setItemText(5, _translate("frmFrequency", "Hamming"))
        self.comboBox.setItemText(6, _translate("frmFrequency", "Hanning"))
        self.comboBox.setItemText(7, _translate("frmFrequency", "Raised cosine"))
        self.label_4.setText(_translate("frmFrequency", "Choose a waveform type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFrequency", "Frequency"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFrequency", "Advanced"))
        self.btnOK.setText(_translate("frmFrequency", "OK"))
        self.btnCancel.setText(_translate("frmFrequency", "Cancel"))
