# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmAntennaArray.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmAntennaArray(object):
    def setupUi(self, frmAntennaArray):
        frmAntennaArray.setObjectName("frmAntennaArray")
        frmAntennaArray.resize(605, 451)
        self.centralwidget = QtWidgets.QWidget(frmAntennaArray)
        self.centralwidget.setObjectName("centralwidget")
        frmAntennaArray.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmAntennaArray)
        QtCore.QMetaObject.connectSlotsByName(frmAntennaArray)

    def retranslateUi(self, frmAntennaArray):
        _translate = QtCore.QCoreApplication.translate
        frmAntennaArray.setWindowTitle(_translate("frmAntennaArray", "Antenna array design"))
