# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmNFFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmNFFilter(object):
    def setupUi(self, frmNFFilter):
        frmNFFilter.setObjectName("frmNFFilter")
        frmNFFilter.resize(383, 305)
        self.centralwidget = QtWidgets.QWidget(frmNFFilter)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 121, 30))
        self.label.setObjectName("label")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(80, 250, 100, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(210, 250, 100, 30))
        self.btnClose.setObjectName("btnClose")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 231, 25))
        self.label_2.setObjectName("label_2")
        self.cbxFreq = QtWidgets.QComboBox(self.centralwidget)
        self.cbxFreq.setGeometry(QtCore.QRect(180, 60, 181, 30))
        self.cbxFreq.setObjectName("cbxFreq")
        self.cbxPlotType = QtWidgets.QComboBox(self.centralwidget)
        self.cbxPlotType.setGeometry(QtCore.QRect(180, 110, 181, 30))
        self.cbxPlotType.setObjectName("cbxPlotType")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 121, 30))
        self.label_3.setObjectName("label_3")
        self.cbxVType = QtWidgets.QComboBox(self.centralwidget)
        self.cbxVType.setGeometry(QtCore.QRect(180, 170, 181, 30))
        self.cbxVType.setObjectName("cbxVType")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 121, 30))
        self.label_4.setObjectName("label_4")
        frmNFFilter.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmNFFilter)
        QtCore.QMetaObject.connectSlotsByName(frmNFFilter)

    def retranslateUi(self, frmNFFilter):
        _translate = QtCore.QCoreApplication.translate
        frmNFFilter.setWindowTitle(_translate("frmNFFilter", "Results filter"))
        self.label.setText(_translate("frmNFFilter", "Frequency(HZ)"))
        self.btnApply.setText(_translate("frmNFFilter", "Apply"))
        self.btnClose.setText(_translate("frmNFFilter", "Close"))
        self.label_2.setText(_translate("frmNFFilter", "Element source power"))
        self.label_3.setText(_translate("frmNFFilter", "Plot type"))
        self.label_4.setText(_translate("frmNFFilter", "Value type"))
