# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx\src\UI\frmMPI copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMPI(object):
    def setupUi(self, frmMPI):
        frmMPI.setObjectName("frmMPI")
        frmMPI.resize(383, 193)
        self.centralwidget = QtWidgets.QWidget(frmMPI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 131, 30))
        self.label.setObjectName("label")
        self.txtMPINum = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMPINum.setGeometry(QtCore.QRect(180, 60, 151, 30))
        self.txtMPINum.setObjectName("txtMPINum")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(110, 120, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(210, 120, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 231, 25))
        self.label_2.setObjectName("label_2")
        frmMPI.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMPI)
        QtCore.QMetaObject.connectSlotsByName(frmMPI)

    def retranslateUi(self, frmMPI):
        _translate = QtCore.QCoreApplication.translate
        frmMPI.setWindowTitle(_translate("frmMPI", "Simulation parallel "))
        self.label.setText(_translate("frmMPI", "MPI Process "))
        self.btnOK.setText(_translate("frmMPI", "OK"))
        self.btnCancel.setText(_translate("frmMPI", "Cancel"))
        self.label_2.setText(_translate("frmMPI", "MPI process settings"))
