# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmSBoundMetal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmSBoundMetal(object):
    def setupUi(self, frmSBoundMetal):
        frmSBoundMetal.setObjectName("frmSBoundMetal")
        frmSBoundMetal.resize(329, 204)
        self.centralwidget = QtWidgets.QWidget(frmSBoundMetal)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(120, 160, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(220, 160, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 160, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.groupCondition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCondition.setGeometry(QtCore.QRect(10, 20, 301, 131))
        self.groupCondition.setTitle("")
        self.groupCondition.setObjectName("groupCondition")
        self.txtFaceId = QtWidgets.QLineEdit(self.groupCondition)
        self.txtFaceId.setGeometry(QtCore.QRect(110, 10, 171, 30))
        self.txtFaceId.setObjectName("txtFaceId")
        self.label = QtWidgets.QLabel(self.groupCondition)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupCondition)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtVoltage = QtWidgets.QLineEdit(self.groupCondition)
        self.txtVoltage.setGeometry(QtCore.QRect(110, 90, 171, 30))
        self.txtVoltage.setObjectName("txtVoltage")
        self.cbxBoundType = QtWidgets.QComboBox(self.groupCondition)
        self.cbxBoundType.setGeometry(QtCore.QRect(110, 50, 171, 30))
        self.cbxBoundType.setObjectName("cbxBoundType")
        self.cbxBoundType.addItem("")
        self.cbxBoundType.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupCondition)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 91, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        frmSBoundMetal.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmSBoundMetal)
        QtCore.QMetaObject.connectSlotsByName(frmSBoundMetal)

    def retranslateUi(self, frmSBoundMetal):
        _translate = QtCore.QCoreApplication.translate
        frmSBoundMetal.setWindowTitle(_translate("frmSBoundMetal", "金属接触"))
        self.btnApply.setText(_translate("frmSBoundMetal", "应用"))
        self.btnCancel.setText(_translate("frmSBoundMetal", "取消"))
        self.btnOK.setText(_translate("frmSBoundMetal", "确定"))
        self.label.setText(_translate("frmSBoundMetal", "面编号"))
        self.label_3.setText(_translate("frmSBoundMetal", "直流源幅度(V)"))
        self.cbxBoundType.setItemText(0, _translate("frmSBoundMetal", "阳极或者源极电压"))
        self.cbxBoundType.setItemText(1, _translate("frmSBoundMetal", "阴极或者漏极电压"))
        self.label_5.setText(_translate("frmSBoundMetal", "标志位"))
