# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmStructForce.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmStructForce(object):
    def setupUi(self, frmStructForce):
        frmStructForce.setObjectName("frmStructForce")
        frmStructForce.resize(308, 216)
        self.centralwidget = QtWidgets.QWidget(frmStructForce)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(110, 170, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 170, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 170, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 60, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txtForce_x = QtWidgets.QLineEdit(self.centralwidget)
        self.txtForce_x.setGeometry(QtCore.QRect(90, 110, 51, 30))
        self.txtForce_x.setObjectName("txtForce_x")
        self.txtPointId = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPointId.setGeometry(QtCore.QRect(90, 30, 181, 30))
        self.txtPointId.setObjectName("txtPointId")
        self.txtPoint_xyz = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPoint_xyz.setEnabled(False)
        self.txtPoint_xyz.setGeometry(QtCore.QRect(90, 70, 181, 30))
        self.txtPoint_xyz.setObjectName("txtPoint_xyz")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 60, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.txtForce_y = QtWidgets.QLineEdit(self.centralwidget)
        self.txtForce_y.setGeometry(QtCore.QRect(155, 110, 51, 30))
        self.txtForce_y.setObjectName("txtForce_y")
        self.txtForce_z = QtWidgets.QLineEdit(self.centralwidget)
        self.txtForce_z.setGeometry(QtCore.QRect(220, 110, 51, 30))
        self.txtForce_z.setObjectName("txtForce_z")
        frmStructForce.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmStructForce)
        QtCore.QMetaObject.connectSlotsByName(frmStructForce)

    def retranslateUi(self, frmStructForce):
        _translate = QtCore.QCoreApplication.translate
        frmStructForce.setWindowTitle(_translate("frmStructForce", "结构-外力"))
        self.btnApply.setText(_translate("frmStructForce", "应用"))
        self.btnCancel.setText(_translate("frmStructForce", "取消"))
        self.btnOK.setText(_translate("frmStructForce", "确定"))
        self.label_3.setText(_translate("frmStructForce", "外力大小"))
        self.label.setText(_translate("frmStructForce", "点编号"))
        self.label_4.setText(_translate("frmStructForce", "点坐标"))
