# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmEMPML.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmEMPML(object):
    def setupUi(self, frmEMPML):
        frmEMPML.setObjectName("frmEMPML")
        frmEMPML.resize(308, 149)
        self.centralwidget = QtWidgets.QWidget(frmEMPML)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(110, 90, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 90, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 90, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.txtSolidId = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSolidId.setGeometry(QtCore.QRect(90, 30, 191, 30))
        self.txtSolidId.setObjectName("txtSolidId")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        frmEMPML.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmEMPML)
        QtCore.QMetaObject.connectSlotsByName(frmEMPML)

    def retranslateUi(self, frmEMPML):
        _translate = QtCore.QCoreApplication.translate
        frmEMPML.setWindowTitle(_translate("frmEMPML", "电磁-完美匹配层"))
        self.btnApply.setText(_translate("frmEMPML", "应用"))
        self.btnCancel.setText(_translate("frmEMPML", "取消"))
        self.btnOK.setText(_translate("frmEMPML", "确定"))
        self.label.setText(_translate("frmEMPML", "体编号"))
