# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmMPI - 副本.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMPI(object):
    def setupUi(self, frmMPI):
        frmMPI.setObjectName("frmMPI")
        frmMPI.resize(519, 287)
        self.centralwidget = QtWidgets.QWidget(frmMPI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 131, 30))
        self.label.setObjectName("label")
        self.txtMPINum = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMPINum.setGeometry(QtCore.QRect(190, 60, 241, 30))
        self.txtMPINum.setObjectName("txtMPINum")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(270, 230, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(380, 230, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 231, 25))
        self.label_2.setObjectName("label_2")
        self.btnRegister = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegister.setGeometry(QtCore.QRect(50, 230, 80, 30))
        self.btnRegister.setObjectName("btnRegister")
        self.btnTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnTest.setGeometry(QtCore.QRect(160, 230, 80, 30))
        self.btnTest.setObjectName("btnTest")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 141, 30))
        self.label_3.setObjectName("label_3")
        self.txtInstallPath = QtWidgets.QLineEdit(self.centralwidget)
        self.txtInstallPath.setGeometry(QtCore.QRect(190, 110, 241, 30))
        self.txtInstallPath.setObjectName("txtInstallPath")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(440, 110, 51, 31))
        self.btnBrowse.setObjectName("btnBrowse")
        frmMPI.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMPI)
        QtCore.QMetaObject.connectSlotsByName(frmMPI)

    def retranslateUi(self, frmMPI):
        _translate = QtCore.QCoreApplication.translate
        frmMPI.setWindowTitle(_translate("frmMPI", "Simulation parallel "))
        self.label.setText(_translate("frmMPI", "MPI Process "))
        self.btnOK.setText(_translate("frmMPI", "OK"))
        self.btnCancel.setText(_translate("frmMPI", "Cancel"))
        self.label_2.setText(_translate("frmMPI", "MPI process settings"))
        self.btnRegister.setText(_translate("frmMPI", "Register"))
        self.btnTest.setText(_translate("frmMPI", "Test"))
        self.label_3.setText(_translate("frmMPI", "Install Path"))
        self.btnBrowse.setText(_translate("frmMPI", "..."))
