# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmDomain copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmDomain(object):
    def setupUi(self, frmDomain):
        frmDomain.setObjectName("frmDomain")
        frmDomain.resize(323, 204)
        self.centralwidget = QtWidgets.QWidget(frmDomain)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 160, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(180, 160, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxDomain = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxDomain.setGeometry(QtCore.QRect(10, 10, 301, 131))
        self.gbxDomain.setObjectName("gbxDomain")
        self.chk1 = QtWidgets.QCheckBox(self.gbxDomain)
        self.chk1.setGeometry(QtCore.QRect(20, 30, 91, 30))
        self.chk1.setObjectName("chk1")
        self.label_5 = QtWidgets.QLabel(self.gbxDomain)
        self.label_5.setGeometry(QtCore.QRect(120, 30, 91, 30))
        self.label_5.setObjectName("label_5")
        self.txtTimeStepNum = QtWidgets.QLineEdit(self.gbxDomain)
        self.txtTimeStepNum.setGeometry(QtCore.QRect(220, 30, 71, 30))
        self.txtTimeStepNum.setObjectName("txtTimeStepNum")
        self.chk2 = QtWidgets.QCheckBox(self.gbxDomain)
        self.chk2.setGeometry(QtCore.QRect(20, 80, 81, 30))
        self.chk2.setObjectName("chk2")
        self.label_7 = QtWidgets.QLabel(self.gbxDomain)
        self.label_7.setGeometry(QtCore.QRect(120, 80, 91, 30))
        self.label_7.setObjectName("label_7")
        self.txtTimeStepNum2 = QtWidgets.QLineEdit(self.gbxDomain)
        self.txtTimeStepNum2.setGeometry(QtCore.QRect(220, 80, 71, 30))
        self.txtTimeStepNum2.setObjectName("txtTimeStepNum2")
        frmDomain.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmDomain)
        QtCore.QMetaObject.connectSlotsByName(frmDomain)
        frmDomain.setTabOrder(self.txtTimeStepNum, self.btnOK)
        frmDomain.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmDomain):
        _translate = QtCore.QCoreApplication.translate
        frmDomain.setWindowTitle(_translate("frmDomain", "观察域"))
        self.btnOK.setText(_translate("frmDomain", "确定"))
        self.btnCancel.setText(_translate("frmDomain", "取消"))
        self.gbxDomain.setTitle(_translate("frmDomain", "求解域选择"))
        self.chk1.setText(_translate("frmDomain", "电磁场"))
        self.label_5.setText(_translate("frmDomain", "时间步数"))
        self.txtTimeStepNum.setText(_translate("frmDomain", "1"))
        self.chk2.setText(_translate("frmDomain", "热/结构"))
        self.label_7.setText(_translate("frmDomain", "时间步数"))
        self.txtTimeStepNum2.setText(_translate("frmDomain", "1"))
