# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmFilter2dPolar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmFilter2dPolar(object):
    def setupUi(self, frmFilter2dPolar):
        frmFilter2dPolar.setObjectName("frmFilter2dPolar")
        frmFilter2dPolar.resize(315, 171)
        self.centralwidget = QtWidgets.QWidget(frmFilter2dPolar)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 130, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(180, 130, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxDomainPF = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxDomainPF.setGeometry(QtCore.QRect(10, 10, 291, 101))
        self.gbxDomainPF.setTitle("")
        self.gbxDomainPF.setObjectName("gbxDomainPF")
        self.label = QtWidgets.QLabel(self.gbxDomainPF)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 28))
        self.label.setObjectName("label")
        self.rdbTheta = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdbTheta.setGeometry(QtCore.QRect(100, 10, 68, 28))
        self.rdbTheta.setObjectName("rdbTheta")
        self.rdbPhi = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdbPhi.setGeometry(QtCore.QRect(190, 10, 68, 28))
        self.rdbPhi.setObjectName("rdbPhi")
        self.label_2 = QtWidgets.QLabel(self.gbxDomainPF)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 41, 28))
        self.label_2.setObjectName("label_2")
        self.cbxValues = QtWidgets.QComboBox(self.gbxDomainPF)
        self.cbxValues.setGeometry(QtCore.QRect(100, 60, 161, 28))
        self.cbxValues.setObjectName("cbxValues")
        frmFilter2dPolar.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmFilter2dPolar)
        QtCore.QMetaObject.connectSlotsByName(frmFilter2dPolar)
        frmFilter2dPolar.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmFilter2dPolar):
        _translate = QtCore.QCoreApplication.translate
        frmFilter2dPolar.setWindowTitle(_translate("frmFilter2dPolar", "2D方向图设置"))
        self.btnOK.setText(_translate("frmFilter2dPolar", "确定"))
        self.btnCancel.setText(_translate("frmFilter2dPolar", "取消"))
        self.label.setText(_translate("frmFilter2dPolar", "切面"))
        self.rdbTheta.setText(_translate("frmFilter2dPolar", "Theta"))
        self.rdbPhi.setText(_translate("frmFilter2dPolar", "Phi"))
        self.label_2.setText(_translate("frmFilter2dPolar", "切面值"))
