# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx2.0\0.src_dgtd\UI\frmPostFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmPostFilter(object):
    def setupUi(self, frmPostFilter):
        frmPostFilter.setObjectName("frmPostFilter")
        frmPostFilter.resize(337, 158)
        self.centralwidget = QtWidgets.QWidget(frmPostFilter)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 120, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(180, 120, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 91, 28))
        self.label.setObjectName("label")
        self.txtMaxNum = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMaxNum.setGeometry(QtCore.QRect(130, 70, 191, 28))
        self.txtMaxNum.setText("")
        self.txtMaxNum.setObjectName("txtMaxNum")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 91, 28))
        self.label_2.setObjectName("label_2")
        self.cbxTime = QtWidgets.QComboBox(self.centralwidget)
        self.cbxTime.setGeometry(QtCore.QRect(130, 20, 191, 28))
        self.cbxTime.setObjectName("cbxTime")
        frmPostFilter.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmPostFilter)
        QtCore.QMetaObject.connectSlotsByName(frmPostFilter)
        frmPostFilter.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmPostFilter):
        _translate = QtCore.QCoreApplication.translate
        frmPostFilter.setWindowTitle(_translate("frmPostFilter", "显示参数"))
        self.btnOK.setText(_translate("frmPostFilter", "确定"))
        self.btnCancel.setText(_translate("frmPostFilter", "取消"))
        self.label.setText(_translate("frmPostFilter", "显示单元数"))
        self.label_2.setText(_translate("frmPostFilter", "观察时刻"))
