# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmStructDirichlet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmStructDirichlet(object):
    def setupUi(self, frmStructDirichlet):
        frmStructDirichlet.setObjectName("frmStructDirichlet")
        frmStructDirichlet.resize(308, 152)
        self.centralwidget = QtWidgets.QWidget(frmStructDirichlet)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(110, 100, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 100, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(20, 100, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txtFaceId = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFaceId.setGeometry(QtCore.QRect(90, 40, 181, 30))
        self.txtFaceId.setObjectName("txtFaceId")
        frmStructDirichlet.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmStructDirichlet)
        QtCore.QMetaObject.connectSlotsByName(frmStructDirichlet)

    def retranslateUi(self, frmStructDirichlet):
        _translate = QtCore.QCoreApplication.translate
        frmStructDirichlet.setWindowTitle(_translate("frmStructDirichlet", "结构-固定位移"))
        self.btnApply.setText(_translate("frmStructDirichlet", "应用"))
        self.btnCancel.setText(_translate("frmStructDirichlet", "取消"))
        self.btnOK.setText(_translate("frmStructDirichlet", "确定"))
        self.label.setText(_translate("frmStructDirichlet", "面编号"))
