# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmMediaLibraryN.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMediaLIbraryN(object):
    def setupUi(self, frmMediaLIbraryN):
        frmMediaLIbraryN.setObjectName("frmMediaLIbraryN")
        frmMediaLIbraryN.resize(860, 475)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMediaLIbraryN.setFont(font)
        frmMediaLIbraryN.setIconSize(QtCore.QSize(18, 18))
        self.centralwidget = QtWidgets.QWidget(frmMediaLIbraryN)
        self.centralwidget.setObjectName("centralwidget")
        self.tabMedia = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMedia.setGeometry(QtCore.QRect(10, 10, 841, 401))
        self.tabMedia.setTabBarAutoHide(True)
        self.tabMedia.setObjectName("tabMedia")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tbIsotropic = QtWidgets.QTableWidget(self.tab)
        self.tbIsotropic.setGeometry(QtCore.QRect(0, 0, 841, 391))
        self.tbIsotropic.setObjectName("tbIsotropic")
        self.tbIsotropic.setColumnCount(0)
        self.tbIsotropic.setRowCount(0)
        self.tabMedia.addTab(self.tab, "")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(10, 430, 100, 30))
        self.btnAdd.setObjectName("btnAdd")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(140, 430, 100, 30))
        self.btnDelete.setObjectName("btnDelete")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(580, 430, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(770, 430, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(680, 430, 71, 30))
        self.btnApply.setObjectName("btnApply")
        frmMediaLIbraryN.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMediaLIbraryN)
        self.tabMedia.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMediaLIbraryN)

    def retranslateUi(self, frmMediaLIbraryN):
        _translate = QtCore.QCoreApplication.translate
        frmMediaLIbraryN.setWindowTitle(_translate("frmMediaLIbraryN", "材料管理"))
        self.tabMedia.setTabText(self.tabMedia.indexOf(self.tab), _translate("frmMediaLIbraryN", "各向同性"))
        self.btnAdd.setText(_translate("frmMediaLIbraryN", "增加材料"))
        self.btnDelete.setText(_translate("frmMediaLIbraryN", "删除选中行"))
        self.btnOK.setText(_translate("frmMediaLIbraryN", "确定"))
        self.btnCancel.setText(_translate("frmMediaLIbraryN", "取消"))
        self.btnApply.setText(_translate("frmMediaLIbraryN", "应用"))
