# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmSimSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmSimSelect(object):
    def setupUi(self, frmSimSelect):
        frmSimSelect.setObjectName("frmSimSelect")
        frmSimSelect.resize(306, 326)
        self.centralwidget = QtWidgets.QWidget(frmSimSelect)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(30, 290, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(160, 290, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxDomainPF = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxDomainPF.setGeometry(QtCore.QRect(10, 10, 281, 271))
        self.gbxDomainPF.setObjectName("gbxDomainPF")
        self.rdb1 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb1.setGeometry(QtCore.QRect(40, 20, 211, 28))
        self.rdb1.setObjectName("rdb1")
        self.rdb2 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb2.setGeometry(QtCore.QRect(40, 50, 211, 28))
        self.rdb2.setObjectName("rdb2")
        self.rdb3 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb3.setGeometry(QtCore.QRect(40, 80, 211, 28))
        self.rdb3.setObjectName("rdb3")
        self.rdb4 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb4.setGeometry(QtCore.QRect(40, 110, 211, 28))
        self.rdb4.setObjectName("rdb4")
        self.rdb5 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb5.setGeometry(QtCore.QRect(40, 140, 211, 28))
        self.rdb5.setObjectName("rdb5")
        self.rdb6 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb6.setGeometry(QtCore.QRect(40, 170, 211, 28))
        self.rdb6.setObjectName("rdb6")
        self.rdb7 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb7.setGeometry(QtCore.QRect(40, 200, 211, 28))
        self.rdb7.setObjectName("rdb7")
        self.rdb8 = QtWidgets.QRadioButton(self.gbxDomainPF)
        self.rdb8.setGeometry(QtCore.QRect(40, 230, 211, 28))
        self.rdb8.setObjectName("rdb8")
        frmSimSelect.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmSimSelect)
        QtCore.QMetaObject.connectSlotsByName(frmSimSelect)
        frmSimSelect.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, frmSimSelect):
        _translate = QtCore.QCoreApplication.translate
        frmSimSelect.setWindowTitle(_translate("frmSimSelect", "物理场选择"))
        self.btnOK.setText(_translate("frmSimSelect", "确定"))
        self.btnCancel.setText(_translate("frmSimSelect", "取消"))
        self.gbxDomainPF.setTitle(_translate("frmSimSelect", "求解类型"))
        self.rdb1.setText(_translate("frmSimSelect", "电磁--电路"))
        self.rdb2.setText(_translate("frmSimSelect", "热"))
        self.rdb3.setText(_translate("frmSimSelect", "结构"))
        self.rdb4.setText(_translate("frmSimSelect", "热--结构"))
        self.rdb5.setText(_translate("frmSimSelect", "热--结构--电磁--电路"))
        self.rdb6.setText(_translate("frmSimSelect", "结构--电磁--电路"))
        self.rdb7.setText(_translate("frmSimSelect", "电磁--电路--热"))
        self.rdb8.setText(_translate("frmSimSelect", "电磁--电路--热--结构"))
