# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmCircuitSource - 副本.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmCIrcuitSource(object):
    def setupUi(self, frmCIrcuitSource):
        frmCIrcuitSource.setObjectName("frmCIrcuitSource")
        frmCIrcuitSource.resize(308, 192)
        self.centralwidget = QtWidgets.QWidget(frmCIrcuitSource)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(110, 140, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(200, 140, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK_2.setGeometry(QtCore.QRect(20, 140, 80, 30))
        self.btnOK_2.setObjectName("btnOK_2")
        self.groupCondition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCondition.setGeometry(QtCore.QRect(10, 20, 291, 91))
        self.groupCondition.setTitle("")
        self.groupCondition.setObjectName("groupCondition")
        self.txtPower = QtWidgets.QLineEdit(self.groupCondition)
        self.txtPower.setGeometry(QtCore.QRect(80, 10, 181, 30))
        self.txtPower.setObjectName("txtPower")
        self.label = QtWidgets.QLabel(self.groupCondition)
        self.label.setGeometry(QtCore.QRect(10, 10, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupCondition)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 60, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtPower_2 = QtWidgets.QLineEdit(self.groupCondition)
        self.txtPower_2.setGeometry(QtCore.QRect(80, 50, 181, 30))
        self.txtPower_2.setObjectName("txtPower_2")
        frmCIrcuitSource.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmCIrcuitSource)
        QtCore.QMetaObject.connectSlotsByName(frmCIrcuitSource)

    def retranslateUi(self, frmCIrcuitSource):
        _translate = QtCore.QCoreApplication.translate
        frmCIrcuitSource.setWindowTitle(_translate("frmCIrcuitSource", "电路-源"))
        self.btnOK.setText(_translate("frmCIrcuitSource", "应用"))
        self.btnCancel.setText(_translate("frmCIrcuitSource", "取消"))
        self.btnOK_2.setText(_translate("frmCIrcuitSource", "确定"))
        self.label.setText(_translate("frmCIrcuitSource", "面编号"))
        self.label_3.setText(_translate("frmCIrcuitSource", "电阻"))
