# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmMediaDispersive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMediaDispersive(object):
    def setupUi(self, frmMediaDispersive):
        frmMediaDispersive.setObjectName("frmMediaDispersive")
        frmMediaDispersive.resize(393, 384)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMediaDispersive.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmMediaDispersive)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 28))
        self.label.setObjectName("label")
        self.txtMediaName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMediaName.setGeometry(QtCore.QRect(120, 20, 261, 28))
        self.txtMediaName.setObjectName("txtMediaName")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(210, 340, 80, 30))
        self.btnClose.setObjectName("btnClose")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(90, 340, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 59, 376, 271))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(1, 0, 371, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btnAddRow = QtWidgets.QPushButton(self.groupBox)
        self.btnAddRow.setGeometry(QtCore.QRect(0, 240, 80, 28))
        self.btnAddRow.setObjectName("btnAddRow")
        self.btnRemoveRow = QtWidgets.QPushButton(self.groupBox)
        self.btnRemoveRow.setGeometry(QtCore.QRect(290, 240, 80, 28))
        self.btnRemoveRow.setObjectName("btnRemoveRow")
        frmMediaDispersive.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMediaDispersive)
        QtCore.QMetaObject.connectSlotsByName(frmMediaDispersive)

    def retranslateUi(self, frmMediaDispersive):
        _translate = QtCore.QCoreApplication.translate
        frmMediaDispersive.setWindowTitle(_translate("frmMediaDispersive", "色散材料"))
        self.label.setText(_translate("frmMediaDispersive", "材料名称"))
        self.btnClose.setText(_translate("frmMediaDispersive", "取消"))
        self.btnOK.setText(_translate("frmMediaDispersive", "确定"))
        self.btnAddRow.setText(_translate("frmMediaDispersive", "增加频点"))
        self.btnRemoveRow.setText(_translate("frmMediaDispersive", "删除选中行"))
