# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmCreateMesh - 副本.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmCreateMesh(object):
    def setupUi(self, frmCreateMesh):
        frmCreateMesh.setObjectName("frmCreateMesh")
        frmCreateMesh.resize(346, 128)
        self.centralwidget = QtWidgets.QWidget(frmCreateMesh)
        self.centralwidget.setObjectName("centralwidget")
        self.btnMesh = QtWidgets.QPushButton(self.centralwidget)
        self.btnMesh.setGeometry(QtCore.QRect(80, 80, 80, 30))
        self.btnMesh.setObjectName("btnMesh")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(190, 80, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 30))
        self.label.setObjectName("label")
        self.txtMaxSize = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMaxSize.setGeometry(QtCore.QRect(160, 20, 141, 30))
        self.txtMaxSize.setObjectName("txtMaxSize")
        frmCreateMesh.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmCreateMesh)
        QtCore.QMetaObject.connectSlotsByName(frmCreateMesh)

    def retranslateUi(self, frmCreateMesh):
        _translate = QtCore.QCoreApplication.translate
        frmCreateMesh.setWindowTitle(_translate("frmCreateMesh", "生成网格"))
        self.btnMesh.setText(_translate("frmCreateMesh", "生成"))
        self.btnCancel.setText(_translate("frmCreateMesh", "取消"))
        self.label.setText(_translate("frmCreateMesh", "网格尺寸(m)"))
