# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmFindElement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmFindElement(object):
    def setupUi(self, frmFindElement):
        frmFindElement.setObjectName("frmFindElement")
        frmFindElement.resize(329, 227)
        self.centralwidget = QtWidgets.QWidget(frmFindElement)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 301, 151))
        self.groupBox.setObjectName("groupBox")
        self.lblReal = QtWidgets.QLabel(self.groupBox)
        self.lblReal.setGeometry(QtCore.QRect(10, 40, 121, 25))
        self.lblReal.setObjectName("lblReal")
        self.lblImag = QtWidgets.QLabel(self.groupBox)
        self.lblImag.setGeometry(QtCore.QRect(10, 100, 121, 25))
        self.lblImag.setObjectName("lblImag")
        self.txtElementId = QtWidgets.QLineEdit(self.groupBox)
        self.txtElementId.setGeometry(QtCore.QRect(150, 100, 141, 30))
        self.txtElementId.setObjectName("txtElementId")
        self.cbxPort = QtWidgets.QComboBox(self.groupBox)
        self.cbxPort.setGeometry(QtCore.QRect(150, 30, 141, 30))
        self.cbxPort.setObjectName("cbxPort")
        self.cbxPort.addItem("")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(110, 180, 80, 30))
        self.btnClose.setObjectName("btnClose")
        frmFindElement.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmFindElement)
        QtCore.QMetaObject.connectSlotsByName(frmFindElement)

    def retranslateUi(self, frmFindElement):
        _translate = QtCore.QCoreApplication.translate
        frmFindElement.setWindowTitle(_translate("frmFindElement", "Find mesh element"))
        self.groupBox.setTitle(_translate("frmFindElement", "Find mesh element by number"))
        self.lblReal.setText(_translate("frmFindElement", "Element type"))
        self.lblImag.setText(_translate("frmFindElement", "Element ID"))
        self.cbxPort.setItemText(0, _translate("frmFindElement", "Triangles"))
        self.btnClose.setText(_translate("frmFindElement", "Close"))
