# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmMeshSize.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMeshSize(object):
    def setupUi(self, frmMeshSize):
        frmMeshSize.setObjectName("frmMeshSize")
        frmMeshSize.resize(346, 128)
        self.centralwidget = QtWidgets.QWidget(frmMeshSize)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(80, 80, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(190, 80, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 30))
        self.label.setObjectName("label")
        self.txtMaxSize = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMaxSize.setGeometry(QtCore.QRect(120, 20, 131, 30))
        self.txtMaxSize.setObjectName("txtMaxSize")
        self.chk_used = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_used.setGeometry(QtCore.QRect(260, 20, 71, 30))
        self.chk_used.setObjectName("chk_used")
        frmMeshSize.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMeshSize)
        QtCore.QMetaObject.connectSlotsByName(frmMeshSize)

    def retranslateUi(self, frmMeshSize):
        _translate = QtCore.QCoreApplication.translate
        frmMeshSize.setWindowTitle(_translate("frmMeshSize", "局部尺寸"))
        self.btnOK.setText(_translate("frmMeshSize", "确定"))
        self.btnCancel.setText(_translate("frmMeshSize", "取消"))
        self.label.setText(_translate("frmMeshSize", "网格尺寸(m)"))
        self.chk_used.setText(_translate("frmMeshSize", "启用"))
