# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\frmCircuitLoad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmCIrcuitLoad(object):
    def setupUi(self, frmCIrcuitLoad):
        frmCIrcuitLoad.setObjectName("frmCIrcuitLoad")
        frmCIrcuitLoad.resize(347, 220)
        self.centralwidget = QtWidgets.QWidget(frmCIrcuitLoad)
        self.centralwidget.setObjectName("centralwidget")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(130, 170, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(230, 170, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(30, 170, 80, 30))
        self.btnOK.setObjectName("btnOK")
        self.groupCondition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCondition.setGeometry(QtCore.QRect(10, 20, 331, 131))
        self.groupCondition.setTitle("")
        self.groupCondition.setObjectName("groupCondition")
        self.txtFaceId = QtWidgets.QLineEdit(self.groupCondition)
        self.txtFaceId.setGeometry(QtCore.QRect(80, 10, 191, 30))
        self.txtFaceId.setObjectName("txtFaceId")
        self.label = QtWidgets.QLabel(self.groupCondition)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupCondition)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 61, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtLoad = QtWidgets.QLineEdit(self.groupCondition)
        self.txtLoad.setGeometry(QtCore.QRect(80, 90, 191, 30))
        self.txtLoad.setObjectName("txtLoad")
        self.txtLengthUV = QtWidgets.QLineEdit(self.groupCondition)
        self.txtLengthUV.setGeometry(QtCore.QRect(80, 50, 191, 30))
        self.txtLengthUV.setObjectName("txtLengthUV")
        self.label_4 = QtWidgets.QLabel(self.groupCondition)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 61, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.btnExchange = QtWidgets.QPushButton(self.groupCondition)
        self.btnExchange.setGeometry(QtCore.QRect(280, 50, 45, 30))
        self.btnExchange.setObjectName("btnExchange")
        frmCIrcuitLoad.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmCIrcuitLoad)
        QtCore.QMetaObject.connectSlotsByName(frmCIrcuitLoad)

    def retranslateUi(self, frmCIrcuitLoad):
        _translate = QtCore.QCoreApplication.translate
        frmCIrcuitLoad.setWindowTitle(_translate("frmCIrcuitLoad", "电路-负载"))
        self.btnApply.setText(_translate("frmCIrcuitLoad", "应用"))
        self.btnCancel.setText(_translate("frmCIrcuitLoad", "取消"))
        self.btnOK.setText(_translate("frmCIrcuitLoad", "确定"))
        self.label.setText(_translate("frmCIrcuitLoad", "面编号"))
        self.label_3.setText(_translate("frmCIrcuitLoad", "电阻"))
        self.label_4.setText(_translate("frmCIrcuitLoad", "宽/高(m)"))
        self.btnExchange.setText(_translate("frmCIrcuitLoad", "调换"))
