# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\emx1.1\src\UI\frmLocalSize - 副本.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmLocalSize(object):
    def setupUi(self, frmLocalSize):
        frmLocalSize.setObjectName("frmLocalSize")
        frmLocalSize.resize(370, 407)
        self.centralwidget = QtWidgets.QWidget(frmLocalSize)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(240, 360, 80, 30))
        self.btnCancel.setObjectName("btnCancel")
        self.gbxFaceMeshSize = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxFaceMeshSize.setGeometry(QtCore.QRect(20, 10, 321, 121))
        self.gbxFaceMeshSize.setObjectName("gbxFaceMeshSize")
        self.lblThe_start = QtWidgets.QLabel(self.gbxFaceMeshSize)
        self.lblThe_start.setGeometry(QtCore.QRect(10, 70, 101, 30))
        self.lblThe_start.setObjectName("lblThe_start")
        self.txtLocalSize = QtWidgets.QLineEdit(self.gbxFaceMeshSize)
        self.txtLocalSize.setGeometry(QtCore.QRect(120, 70, 181, 30))
        self.txtLocalSize.setText("")
        self.txtLocalSize.setObjectName("txtLocalSize")
        self.chxLocal = QtWidgets.QCheckBox(self.gbxFaceMeshSize)
        self.chxLocal.setGeometry(QtCore.QRect(10, 20, 291, 30))
        self.chxLocal.setObjectName("chxLocal")
        self.gbxFaces = QtWidgets.QGroupBox(self.centralwidget)
        self.gbxFaces.setGeometry(QtCore.QRect(20, 150, 321, 181))
        self.gbxFaces.setObjectName("gbxFaces")
        self.treeView = QtWidgets.QTreeView(self.gbxFaces)
        self.treeView.setGeometry(QtCore.QRect(10, 20, 301, 141))
        self.treeView.setObjectName("treeView")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(150, 360, 80, 30))
        self.btnApply.setObjectName("btnApply")
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(60, 360, 80, 30))
        self.btnOK.setObjectName("btnOK")
        frmLocalSize.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmLocalSize)
        QtCore.QMetaObject.connectSlotsByName(frmLocalSize)

    def retranslateUi(self, frmLocalSize):
        _translate = QtCore.QCoreApplication.translate
        frmLocalSize.setWindowTitle(_translate("frmLocalSize", "Meshing local size "))
        self.btnCancel.setText(_translate("frmLocalSize", "Cancel"))
        self.gbxFaceMeshSize.setTitle(_translate("frmLocalSize", "Mesh size"))
        self.lblThe_start.setText(_translate("frmLocalSize", "Mesh size"))
        self.chxLocal.setText(_translate("frmLocalSize", "Local mesh size"))
        self.gbxFaces.setTitle(_translate("frmLocalSize", "Faces"))
        self.btnApply.setText(_translate("frmLocalSize", "Apply"))
        self.btnOK.setText(_translate("frmLocalSize", "OK"))
