# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\cae\fem-gdtd\src2\UI\widgetFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filterWidget(object):
    def setupUi(self, filterWidget):
        filterWidget.setObjectName("filterWidget")
        filterWidget.resize(303, 69)
        filterWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox = QtWidgets.QComboBox(filterWidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 121, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(filterWidget)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 40, 121, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(filterWidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 10, 101, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(filterWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 40, 101, 25))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(filterWidget)
        QtCore.QMetaObject.connectSlotsByName(filterWidget)

    def retranslateUi(self, filterWidget):
        _translate = QtCore.QCoreApplication.translate
        filterWidget.setWindowTitle(_translate("filterWidget", "Form"))
        self.comboBox.setItemText(0, _translate("filterWidget", "新建项目"))
        self.comboBox.setItemText(1, _translate("filterWidget", "新建项目"))
        self.comboBox.setItemText(2, _translate("filterWidget", "新建项目"))
        self.pushButton.setText(_translate("filterWidget", "PushButton"))
        self.pushButton_2.setText(_translate("filterWidget", "PushButton"))
